### ISSUE TITLE
How can I change 'Text'(div) component to other semantic element? 

### ISSUE THREAD

**Issue by WeiLi512** [rebassjs/rebass#1060]
https://github.com/rebassjs/rebass/issues/433
In this issue, I can see that the Text component(div) can be another semantic element using 'is' prop.
But now working.
![image](https://user-images.githubusercontent.com/50083174/101929877-82c2d900-3c2b-11eb-905c-1abdf4f26264.png)

**Comment by hellobart** [comment]
Try `as="h1"`

**Comment by WeiLi512** [comment]
Thanks @hellobart
