### ISSUE TITLE
Typescript error when using sx prop in a Box component

### ISSUE THREAD

**Issue by danielmariz** [rebassjs/rebass#1109]
Hi there, 
I've installed only the reflexbox and its types to use Box and Flex only, the problem I'm getting is that box does not implement shadow from styled system on its composition so I'm assuming the only way to get those props is via sx prop.
But I'm getting this typescript error when trying to do that
`Property 'sx' does not exist on type 'IntrinsicAttributes & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & Omit<...> & { ...; }'.ts(2322)`
```
<Box as='form' onSubmit={submitHandler} sx={{borderRadius: '24px', boxShadow: 10, p: '24px'}} >
```
How can I get around it?

Cheers

**Comment by kevzzsk** [comment]
Hey, I am facing this same issue. How did you solve it?

I have installed reflexbox and unable to use `sx` prop with typescript

**Comment by danielmariz** [comment]
@kevzzsk I'm not using this package was just an experiment I don't think I was able to get around it at that time. I started using styled-system together with styled component and created my own ui components.
Sorry not being able to help that much.
