### ISSUE TITLE
Adding `* { box-sizing: border-box; }` to the global styles manually is redundant

### ISSUE THREAD

**Issue by kripod** [rebassjs/rebass#445]
While [exploring the source code of `Provider`](https://github.com/jxnblk/rebass/blob/fa2e68409f48a884e799b8ef63d05f479033eb5c/src/Provider.js#L15), I came across the `Root` component [which already defines `box-sizing: border-box` for its descendants](https://github.com/jxnblk/rebass/blob/fa2e68409f48a884e799b8ef63d05f479033eb5c/src/Root.js#L6-L8):

```js
  '& *': {
    boxSizing: 'border-box'
  }
```

I would like to suggest mentioning this behavior [in the documentation](https://jxnblk.com/rebass/getting-started/#provider) and removing `* { box-sizing: border-box; }` from the recommended `injectGlobal` statement.

**Comment by kripod** [comment]
Also, in order to provide better experience for mobile users, use `text-size-adjust: 100%`, [as recommended by normalize.css](https://github.com/necolas/normalize.css/blob/7369f566898b8cefc2649b6a66e112857de4c46f/normalize.css#L8-L13):

```js
import { injectGlobal } from 'styled-components'

injectGlobal`
  body {
    margin: 0;
    text-size-adjust: 100%;
  }
`
```

**Comment by jxnblk** [comment]
This is no longer in the v3 docs, so closing this out
