### ISSUE TITLE
Support for unpkg.com ?

### ISSUE THREAD

**Issue by asvny** [rebassjs/rebass#471]
As of now, the dist files served by unpkg.com/rebass can't be used (it is in commonjs format) .So, it requires a change in the build system ..Wondering, whether you'll accept a PR ?

**Comment by jxnblk** [comment]
Are you looking for support directly in the browser via a script tag? Can look into that, but might be best to hold off until v3 is out because I'm changing the build setup a bit to hopefully handle things like this

**Comment by asvny** [comment]
`Are you looking for support directly in the browser via a script tag? `
Yes

**Comment by tamlyn** [comment]
This would be useful to CodePen/JSFiddle use cases.

**Comment by jxnblk** [comment]
I'd accept a PR for this, if it doesn't require overhauling the build setup, but closing this for now
