### ISSUE TITLE
Not all props show up in docs

### ISSUE THREAD

**Issue by davidnagli** [rebassjs/rebass#473]
For example on the [`Drawer` documentation page](http://jxnblk.com/rebass/components/Drawer), the props table doesn't have the `open` and `side` props, while the example clearly uses them.

This is extremely frustrating because I've literally been trying to guess what props each component has (I was looking for a prop similar to `open` but for `Modal`)

Are these props not documented because of a glitch in some automatic documentation generation system or because they never existed in the first place?

**Comment by davidnagli** [comment]
Btw I'm a HUGE fan of Rebass and I really appreciate all the hard work that you put into this 🙂 🚀 👍

**Comment by jxnblk** [comment]
> Are these props not documented because of a glitch in some automatic documentation generation system or because they never existed in the first place?

The former, see https://github.com/jxnblk/styled-system/issues/221

**Comment by jxnblk** [comment]
The new docs no longer use system-docs, so closing this out
