### ISSUE TITLE
Theming/Provider not working

### ISSUE THREAD

**Issue by Jrayp** [rebassjs/rebass#476]
So this is an extension of my last issue: 
It seems that the Provider component, or theming in general has stopped working since last update.

Ive been looking through the styled-system and rebass docs to see if im missing an obvious change but I cant find one. (I'm new so may be missing something obvious, if so sorry)

Please let me know if im overlooking something, or just need to wait for a fix :)

edit: Ok nvm, using string values in the breakpoint section of the theme has fixed the issue. This wasnt required before (as integers were just treated as pixel values)

Not sure if this was intended so ill just leave this issue up for now.

**Comment by jxnblk** [comment]
That was an unintentional change due to bumping the styled-system version
