### ISSUE TITLE
Some TS typings are missing

### ISSUE THREAD

**Issue by 3dos** [rebassjs/rebass#477]
I post this issue here as there are 2k+ issues on the DefinitelyTyped repo but some typings are missing from `@types/rebass` like `Flex` or `Box`.

I don't have time for the moment to send a PR but I think you should know this. Thank you for bringing this amazing UI kit to life!

**Comment by jxnblk** [comment]
Sorry, I don't maintain ts definitions, so you should probably open an issue on definitely typed
