### ISSUE TITLE
Card documentation is broken

### ISSUE THREAD

**Issue by raisiqueira** [rebassjs/rebass#478]
Hi, the Card documentation for Rebass v2 is broken.

https://rebass-v2.now.sh/Card

![image](https://user-images.githubusercontent.com/2914170/45304993-c3cd5f80-b4ef-11e8-8b03-b74e54416157.png)

**Comment by jxnblk** [comment]
Thanks! Looks like it's picking up the twitter card image instead of the `.md` file. Can be fixed by renaming the `Card.js` file

**Comment by jxnblk** [comment]
Should be fixed now https://rebass-v2.now.sh/components/Card
