### ISSUE TITLE
is={Tag} don't forward class name

### ISSUE THREAD

**Issue by lionelB** [rebassjs/rebass#480]
Hello, 

I was trying rebass and it seems that the `is` props do not forward the class attribute and lead styles no being found since class names are in a `classname`prop and not in a `class` prop.

I update the codesandbox to illustrate the problem : https://codesandbox.io/s/ll1yxmkp6q

when you resize the window, only the Heading without `is="h1"`prop  update correctly.

**Comment by lionelB** [comment]
hum closing the issue since it looks like a typo. Changing `is` to `as`  resolved the issue

**Comment by jxnblk** [comment]
Just to clarify, if you're using styled-components v4, you'll want to use the `as` prop – older versions with Rebass v2 use the `is` prop

**Comment by lionelB** [comment]
I was targeting the v3. the typo (`is` in place of `as`) is in the codesandbox example linked in the README.md 
https://codesandbox.io/s/github/rebassjs/rebass/tree/master/examples/sandbox-v3
