### ISSUE TITLE
rebass@v2 BackgroundImage isn't displaying the image

### ISSUE THREAD

**Issue by sbrichardson** [rebassjs/rebass#487]
Not sure which update caused it, but the BackgroundImage component isn't displaying the image you provide to the `src` prop. 

This bug can also be seen in the rebass (v2) docs for the [Card example](https://rebass-v2.now.sh/getting-started), the image is blank.

Not a huge issue, since upgrading to v3 soon!

```jsx
<Box width={256}>
  <Card>
    <BackgroundImage src={photo} />
    <Box p={2}>
      <Subhead>Card</Subhead>
      <Small>Small meta text</Small>
    </Box>
  </Card>
</Box>
```

**Comment by sbrichardson** [comment]
Looks like it's just a prop change, `src` changed to `image` for `BackgroundImage`. Changing fixed, just need to fix the example.

**Comment by jxnblk** [comment]
Closing this, but feel free to PR an update to the v2 docs if you'd like to
