### ISSUE TITLE
Revert back esm support

### ISSUE THREAD

**Issue by TrySound** [rebassjs/rebass#494]
Since styled-system issue was resolved could you revert this change?

https://github.com/rebassjs/rebass/commit/48996e575fdaa420d6724d0424a3428e7a19f41e

**Comment by TrySound** [comment]
@jxnblk So what's the problem? Let me help to resolve it. Reverting esm after every release is not a solution.

**Comment by jxnblk** [comment]
I'll likely work on this some over the weekend. Might want to hold off on the build setup until more of the sub packages are in so that we can solve the issue for all packages – this is still on my radar, so wanna keep this issue open to track it
