### ISSUE TITLE
Missing flexbox styles on <Flex> component

### ISSUE THREAD

**Issue by BartvdWaerden** [rebassjs/rebass#496]
I really enjoy working with Rebass, thanks for all the effort you've put in this project!  

After upgrading to _Styled Components v4_ and _Rebass v3_ it seems like every prop on every component works except the props specific to the `<Flex>` (eg. `display: flex;` `alignItems="center"`) component. 

**Example code**
```
    <Flex px={3} py={4} alignItems="center">
      <Box px={3} py={5} color="white" bg="blue">
        <Heading as="h1" fontSize={[4, 5, 6]}>
          Hello, Rebass
        </Heading>
      </Box>
      <Box px={3} py={5} color="white" bg="blue">
        <Heading as="h1" fontSize={[4, 5, 6]}>
          Hello, Rebass
        </Heading>
      </Box>
    </Flex>
```
**Inspector**
![screen shot 2018-09-14 at 23 55 45](https://user-images.githubusercontent.com/2140835/45576946-d6da8980-b879-11e8-9bd1-7f0a1fa742ad.png)

I'm using the Gatsby Starter Default v2 and added Rebass and Styled Components to it. I've been trying to get it to work but without any luck.

**Debugging steps taken**

- Updated all packages to latest versions
- Removed and reinstalled node modules
- Removed cache (browser and Gatsby)
- Removed babel-plugin-styled-components

Thanks in advance!

**Comment by jxnblk** [comment]
Thanks, I'm seeing this bug in *some, not all,* situations as well. As far as I can tell, it's probably a styled-components issue since similar things seem to work in styled-components v3 – any help in figuring out why this isn't working would be much appreciated

**Comment by BartvdWaerden** [comment]
Some more information, it's happening on my localhost only, currently on my live environment (Netlify) the flex styles are applied and working as intended.

**Comment by jxnblk** [comment]
I think I’m noticing the issue with different babel configurations but still can’t figure out exactly what is going on

**Comment by BartvdWaerden** [comment]
Found a solution while checking the deployment logs in Netlify. 

Netlify installs the dependencies using Yarn (`yarn install`). Locally I was using NPM (`npm install`). When I switched to Yarn my problem was solved. Not sure why though...

**Comment by jxnblk** [comment]
Might be helpful to see the output of `npm ls` for both

**Comment by BartvdWaerden** [comment]
Made a gist, hopefully this is helpful, please let me know if I can help any further.

https://gist.github.com/BartvdWaerden/d7d60495225988452c2acadb9ffaf65b

**Comment by gregoralbrecht** [comment]
I kinda ran into this issue as well, except for me, the `flex` prop is missing while all other props (e.g. `justifyContent`) work. The `flex`prop is not mentioned in the docs and it's working perfectly if I use `import { Flex } from '@rebass/grid'` so I'm not sure what's happening here.

**Comment by jxnblk** [comment]
@gregoralbrecht currently the `flex` prop is *not* in Rebass v3 (see #488), so that is expected behavior with the latest beta. Also note that Rebass v3 doesn't use `@rebass/grid` as a dependency

**Comment by jxnblk** [comment]
@BartvdWaerden would you mind testing this out with the latest versions of both `rebass` and `styled-components` betas whenever you get a chance? From my limited testing, I'm not encountering this issue anymore

**Comment by BartvdWaerden** [comment]
@jxnblk I've tested it, and everything seems to be working as it should right now! 

I think you can close this issue, thanks for your fast respons and keep making awesome stuff!
