### ISSUE TITLE
babel-plugin-styled-component and Rebass@v3

### ISSUE THREAD

**Issue by mdotasia** [rebassjs/rebass#498]
I switched from styled-system and styled-components v3 to Rebass v3 and seem to have lost debugging friendly class names generated via `babel-plugin-styled-components` on the way. Any idea why it does not work or how I get get it work again?

**Comment by jxnblk** [comment]
Rebass v3 is intended for use with styled-components v4. It will remain in beta until the official styled-components v4 has been released. I've added a note to the readme to help clarify
