### ISSUE TITLE
Image,Heading & Link component not working as react-emotion doesn't support `as` prop

### ISSUE THREAD

**Issue by ryanwang520** [rebassjs/rebass#501]
Tried to use the latest version of `rebass` with `react-emotion`. As `rebass` uses the `as` prop, `Image` `Heading` and `Linking` components are all rendered as `div` since  `react-emotion` doesn't support using `as` prop to change the underlying component.

I use
```
        "rebass": "^3.0.0-8",
        "styled-components": "^9.2.10",
        "emotion": "^9.2.10",
```

Will `rebass` continue to support `emotion`?

**Comment by jxnblk** [comment]
See https://github.com/emotion-js/emotion/issues/837

**Comment by ryanwang520** [comment]
yep , I've got your point. Thanks.
