### ISSUE TITLE
Is 'is' prop removed?

### ISSUE THREAD

**Issue by JohnPhoto** [rebassjs/rebass#505]
I am wondering if the `is` prop removed in the betas for version 3?

I am using the following dependencies:
```
"rebass": "^3.0.0-9",
"styled-components": "^3.4.9", // <-- (V4 beta did not work for me due to some other bugs)
"styled-system": "^3.1.6",
```

When I try the following codesnippet:
```
import React from 'react';
import styled from 'styled-components';
import { Text as RebassText } from 'rebass';


export const Text = props => <RebassText is="p" {...props} />;

Text.displayName = 'Text';

Text.defaultProps = {
  color: 'onBackground',
};

export default Text;

```

the html-element is still a `div`:
```
<div classname="sc-htpNat KtFsv sc-bdVaJa kLRksD" is="p" color="primary">Reference</div>
```

**Comment by moklick** [comment]
rebass is now using styled-components v4, so I thought that the [`as` prop](https://www.styled-components.com/docs/api#as-polymorphic-prop) is supported. But this also doesn't work for me.

**Comment by jxnblk** [comment]
See #474

**Comment by alexanderte** [comment]
`as` prop does’t work for me either. Couldn’t find anything in #474 about this issue.

    import { Link } from "rebass";

    export default props => <Link as="pre">{props.children}</Link>;

`Link` without `as` specified renders as an HTML `div`. With `as` set to `a` or `pre` it still renders a `div`.

**Comment by jxnblk** [comment]
From #474:

> Why has system-components (@rebass/components) been removed?
> It adds a lot of overhead and complexity to the codebase, and most end-users don't benefit from it being used in Rebass.

The `is` prop has been removed in v3 in favor of the styled-components `as` prop. You'll need to `npm i styled-components@beta` to use v4 until it's released
