### ISSUE TITLE
rebass@3.x need support min/maxWidth for Box

### ISSUE THREAD

**Issue by janryWang** [rebassjs/rebass#507]
https://github.com/rebassjs/rebass/blob/master/src/index.js#L39

**Comment by jxnblk** [comment]
Thanks, but I don't think max/min width belong in the base Box component. You can extend the Box component and add things like this as you need to

**Comment by janryWang** [comment]
I mainly hope that min/maxwidth can be changed automatically according to breakpoints. If we pass the ‘css’ attribute, we will have to do these processing ourselves.

**Comment by jxnblk** [comment]
FWIW, extending the Box component to do this would look something like this:

```js
import styled from 'styled-components'
import { Box as RebassBox } from 'rebass'
import { maxWidth, minWidth } from 'styled-system'

export const Box = styled(RebassBox)(maxWidth, minWidth)
```
