### ISSUE TITLE
Is Box component enhanced/optimized for hundreds or even thousands of children?

### ISSUE THREAD

**Issue by fpena** [rebassjs/rebass#511]
I'm building a chat app, and using a `Box` component as parent for multiple conversation item elements. 

I'm storing the conversation locally, so I wonder if this component is optimized to hold hundreds or even thousand messages inside of it. 

For example, when adding a new message, I'd like to know if all elements are re-rendered, or only ones visible.

**Comment by TrySound** [comment]
@fpena Box is a simple div. It doesn't virtualize your stuff. Use [react-window](https://github.com/bvaughn/react-window)

**Comment by fpena** [comment]
Thanks @TrySound !
