### ISSUE TITLE
Support functions as values in the theme object

### ISSUE THREAD

**Issue by dlbnco** [rebassjs/rebass#512]
Hi, first of all, great work! My workflow improved a lot since I started using `rebass` and `styled-system`.

So, I'm experimenting with [`styled-theming`](https://github.com/styled-components/styled-theming) to create themes with multiple modes/variants.

For example, for text color, I would have 2 variants (primary or secondary) for each mode (light and dark). Then, when styling a theme component, I just pass the function from `styled-theming` and the component will render the corresponding color depending on the theme's `mode` and the `variant` passed to the component.

In the example below, `MyTextComponent` will render with the `#AAAABB` color because the theme mode is set to `light` and the variant prop in the component is set to `secondary`:

```js
import React from 'react';
import styled, {ThemeProvider} from 'styled-components';
import theme from 'styled-theming';

const textColor = theme.variants('mode', 'variant', {
  primary: {
    light: '#494949',
    dark: '#FFFFFF',
  },
  secondary: {
    light: '#AAAABB',
    dark: '#76767E',
  },
});

const MyTextComponent = styled.div.attrs({
    variant: 'secondary' 
  })`
  color: ${textColor};
`;

export default () => (
  <ThemeProvider theme={{ mode: 'light' }}>
    <MyTextComponent>
      Hello
    </MyTextComponent>
  </ThemeProvider>
)
```

I'm also using `rebass` components, and I can already do something like this to use my `textColor` function:

```js
import React from 'react';
import { Text as CoreText } from 'rebass';
import { textColor } from '../themes'

const Text = styled(CoreText)`
  color: ${textColor};
`

export default () => (
  <Text variant="secondary">
    Hello
  </Text>
)
```

But now I want to store the `textColor` function in `ThemeProvider` so I can better integrate everything. I'm not sure if this is already possible, so let me know if I'm missing something.

The way I'm trying to do it is to pass those `styled-theming` functions as values into the `theme` prop (as described [here](https://rebassjs.org/theming)) so all my `rebass` components can access them without having to import the theme function everytime in each component:

```js
// example theme.js

const textColor = theme.variants('mode', 'variant', {
  primary: {
    light: '#494949',
    dark: '#FFFFFF',
  },
  secondary: {
    light: '#AAAABB',
    dark: '#76767E',
  },
});

export default {
  mode: 'light',
  colors: {
    textColor,
  },
};
```

```js
import React from 'react';
import styled, { ThemeProvider } from 'styled-components';
import { Text } from 'rebass';
import theme from './theme'

export default () => (
  <ThemeProvider theme={theme}>
    <Text color="textColor" variant="secondary">
      Hello
    </Text>
  </ThemeProvider>
)
```

**Comment by jxnblk** [comment]
I might not have a complete answer to the question here, but my initial thoughts are:

1. styled-theming seems like it's more intended to store values locally in a component, whereas styled-system is intended for storing all values in the theme
2. If you're switching `mode` at the ThemeProvider, why not switch the other theme values like `textColor` instead?
3. You might be able to achieve what you're going for with [nested functional themes](https://www.styled-components.com/docs/advanced#function-themes) where the parent one switches the "mode"

**Comment by jxnblk** [comment]
Closing this since it seems out of scope for this library
