### ISSUE TITLE
`Box` component inconsistent in `rebass` vs `@rebass/grid`

### ISSUE THREAD

**Issue by jannisg** [rebassjs/rebass#513]
I was just exploring both `rebass@next` (`3.0.0-9`) and `@rebass/grid` (`6.0.0-4`) and was fairly confused as to why my layout broke when I tried removing the `@rebass/grid` module as I had thought it was redundant when using the entirety of `rebass` in my project.

I eventually found that `@rebass/grid` sets [`box-sizing: border-box`](https://github.com/rebassjs/grid/blob/master/src/index.js#L17) on its `Box` components while `rebass`' `Box` component does not.

Can you please clarify if the idea is that there is feature parity and the same API between the following?

```js
import { Flex, Box } from '@rebass/grid';

// vs

import { Flex, Box } from 'rebass';
```

If there is not meant to be any parity/consistency in the base props etc, is the intent that people use both `rebass` AND `@rebass/grid` side by side for a "complete" layout + component solution?

**Comment by jxnblk** [comment]
Yeah, that's not necessarily intentional. I'll look into setting `box-sizing` in Rebass and make sure that doesn't have any unintended consequences. As a workaround for your own project, you could set `box-sizing: border-box` globally, which a lot of people tend to do

**Comment by jannisg** [comment]
Cool, I am currently using the 2 libraries side-by-side and will refactor out the `@rebass/grid` when a patch has been released. That said, as you said `* { box-sizing: border-box; }` is a decent solution for now too :)
