### ISSUE TITLE
Server Side rendering backgroundImage

### ISSUE THREAD

**Issue by jamalabo1** [rebassjs/rebass#520]
Hello, 
there is problem with server-side rendering where backgroundImage does not show the image, 
the problem appeared instantly after turning the app to server-side rendering (was working in client-side)

`rebass version: 2.3.4`
`react version: 16.5.2`
`styled-components version: 3.4.9`

**Comment by jxnblk** [comment]
Can you provide a sandbox or code snippet of how you're using the `BackgroundImage` component?

**Comment by jamalabo1** [comment]
@jxnblk 
actually i found the problem,
the api changed 

my new code: 

```
<Banner
            color='black'
            minHeight={"60vh"}
            alignItems="left"
            justifyContent="center"
            backgroundImage={function(){
              return `url(${imageUrll})`
            }()} />
```

**Comment by jxnblk** [comment]
You shouldn't need the immediately invoked function expression, but closing this out since it sounds like you've figured it out
