### ISSUE TITLE
Trying to use theme color in extended component's css

### ISSUE THREAD

**Issue by oiojin831** [rebassjs/rebass#523]
So I am trying to use my color that I defined in themes.
Should I manually import the js object to use it?
```
import React from 'react'
import {Box} from 'rebass'
import theme from '../../../Styles/theme'

export default props => (
  <Box
    {...props}
    css={{
      '&:hover': {
        backgroundColor: theme.colors.primaryBg,
      },
    }}
  />
)
```
The above code is what I did. and what I was expected to be done was
```
import .....

export default props => (
  <Box
    {...props}
    css={{
      '&:hover': {
        backgroundColor: 'primaryBg',
      },
    }}
  />
)
```
Thanks for the help in advance 😄

**Comment by jxnblk** [comment]
Your first example should work fine. If you want to use theme value dynamically from props, you'll need to use something like the `withTheme` HOC to add the `theme` object to your component

**Comment by bibekluitel** [comment]
I think this should be handled by Rebass component itself.  If it can manage to get the theme value for other props, I suppose we should be able to get the theme values inside the ```css``` props. 

In my view enabling the theme inside the ```css``` props makes it easier for developers to understand.

**Comment by jxnblk** [comment]
The `css` prop is now handled with the styled-components babel plugin: https://www.styled-components.com/docs/api#css-prop
