### ISSUE TITLE
Feature request: max-width

### ISSUE THREAD

**Issue by gi-alec** [rebassjs/rebass#525]
Is there any interest in adding max-width as prop a responsive prop? I find myself using max-width very often when writing a responsive site. It's not bad throwing it in the css prop where necessary, but when I need it to be responsive, the code is a bit cumbersome.

I would just make a custom prop, but the styled-system docs don't show any information about create a custom responsive prop.

Is this something you find yourself using often as well?

Cheers

**Comment by jxnblk** [comment]
I feel like this isn’t a super common use-case (e.g. maybe this is only applied to one “Container” component for the whole page layout, and not for all components), and I’d suggest extending the component you want that prop for with styled-system’s `maxWidth` function

**Comment by gi-alec** [comment]
I feel like this could just be evidence of my lack of css prowess.. thanks for giving it a look :)
