### ISSUE TITLE
withComponent is broken in Rebass 3

### ISSUE THREAD

**Issue by felixjung** [rebassjs/rebass#526]
Hi,

I've been looking into Rebass for a small project and really like the concepts it uses. Great job!

I'm more of an Emotion than a Styled Components user and tried using Rebass with Emotion. When I noticed that Rebass' `Button` uses a `div` by default I followed the standard practice of using the `.withComponent()` method of Emotion components to change the base element of `Button` to `button`. Unfortunately, it appears that this does not work as expected.

The resulting component does render a with a button element. However, all of Rebass' default styles for its `Button` component are lost. Instead, the browser renders a standard button element.

Here's a [Sandbox demonstrating the issue](https://codesandbox.io/s/024wwpvpl). 

Any idea what's going on here?

Thanks!

**Comment by jxnblk** [comment]
I suspect that using the `styled(Button)` approach would be the way to go here. Not sure how Emotion’s `withComponent` method works behind the scenes and these components haven’t been written with that API in mind

**Comment by felixjung** [comment]
Thanks, but as far as I know, `styled` won't change the underlying element of `Button`. My initial goal was to ensure we render a `button` and not a `div`. I remember seeing a different issue where you or someone else suggested using `withComponent` because Emotion lacks support for the `as` prop.

I've since tried rebass with styled-components and found that the `Button` component then renders a `button` element.

**Comment by felixjung** [comment]
I've updated the sandbox to illustrate the issue a bit more. Not sure why this is happening when making the emotion version is just a build step with an alias. Might be the pre-release emotion version I've been playing with?

**Comment by jxnblk** [comment]
Not sure if you got anywhere with this but Emotion 10 supports the `as` prop, which means Rebass v3 *should* work with Emotion now. It's not fully documented yet, but you can try it out by installing `@rebass/emotion`

**Comment by felixjung** [comment]
Yeah, saw that. Been playing with Emotion 10 in a code sandbox last week. 😄 Didn't try `@rebass/emotion` though. Thanks

**Comment by felixjung** [comment]
Hm, just thinking about this as I'm creating a another CodeSandbox... There are quite significant changes between Emotion 9 and 10. Specifically, Emotion now [supports a `css` prop directly](https://emotion.sh/docs/css-prop) without babel plugin. It does so by exporting it's own `jsx` function that you use to transpile JSX with babel. I'm not sure how well that's going to fly with Rebass. Will try now, but might be a blocker (unless you've tested this already).

**Comment by felixjung** [comment]
OK, made the CodeSandbox and everything seems to work just fine with Emotion 10 and `@rebass/emotion`. Sweet! Thanks a lot.
