### ISSUE TITLE
reponsive width prop has been set as an array on HTML tag's attribute.

### ISSUE THREAD

**Issue by Albert-Gao** [rebassjs/rebass#529]
```xml
<Box width={[0.05, 0.2]}> </Box>
```

Will generate a HTML like this:
```xml
<div width="0.05,0.2" class="sc-bdVaJa jIJQxE"> </div>
```

The responsive style has been generated and works well.

However, the `width` attribute is not right, shouldn't a width like this be removed from the final HTML code?

I'm using `"rebass": "^3.0.0-11",`, thanks for this awesome lib! :)

**Comment by darkowic** [comment]
This is general `styled-components` issue how to filter styles properties easily - https://github.com/styled-components/styled-components/issues/439

**Comment by Albert-Gao** [comment]
Thanks! Broke my heart when I see the issue is `open`

**Comment by jxnblk** [comment]
Closing this out since there is no official way to prevent this with the current version of styled-components
