### ISSUE TITLE
SSR styling removed on refresh

### ISSUE THREAD

**Issue by jonleopard** [rebassjs/rebass#531]
Hello,
First off, thanks a bunch for Rebass! It's been an essential tool for me across several projects.

The image below starts with an already HMR'd page. The correct styles are applied on first paint with no issues. After manually refreshing the page, any style property taken from theme.js is removed and replaced with system defaults. There's also this warning in the console:

```
Warning: Prop `className` did not match. Server: ... 
```

![kapture 2018-11-21 at 10 11 26](https://user-images.githubusercontent.com/2111234/48831569-5bb0ba80-ed77-11e8-989c-9b7ca2f806bf.gif)

I don't get this issue when using only styled-components. So I suspect there might be an issue with how rebass and styled-components are working together in an SSR environment.

Any clue on whats going on here?

**Comment by jxnblk** [comment]
That error looks like you might not be using the styled-components babel plugin, but otherwise i’d Suspect it’s some issue with styled-components

**Comment by jonleopard** [comment]
Hmm, well I've installed the babel-plugin. I'll go post this over there and see if they can point me in the right direction. Thanks!

```
{
    "env": {
      "development": {
        "plugins": [
          [
            "babel-plugin-styled-components",
            { "ssr": true, "displayName": true, "preprocess": false }
          ]
        ],
        "presets": ["razzle/babel"]
      },
      "production": {
        "plugins": [
          [
            "babel-plugin-styled-components",
            { "ssr": true, "displayName": true, "preprocess": false }
          ]
        ],
        "presets": ["razzle/babel"]
      }
    },
    "plugins": [
      [
        "babel-plugin-styled-components",
        { "ssr": true, "displayName": true, "preprocess": false }
      ]
    ]
}
```
