### ISSUE TITLE
Module not found: Can't resolve 'styled-components' in '/node_modules/@rebass/components/dist'

### ISSUE THREAD

**Issue by ClearedFram3** [rebassjs/rebass#533]
Just tried using the library in CRA 2 and this is the error I get. There's a folder named 'emotion' in dist but no 'styled-components' folder—maybe that's the issue?

**Comment by ClearedFram3** [comment]
Ok... haha resolved the issue by installing styled-components. The documentation never mentions needing 'styled-components' outside of theming and it seems important to mention.

Thanks for library! Hopefully I can contribute in the future 😄

**Comment by siriniok** [comment]
Yes, I believe it has to be mentioned somewhere on the Getting Started page, because it's confusing a bit.

**Comment by embryCODE** [comment]
This is not mentioned on the Getting Started page. I know this issue is closed but I suggest reopening until the necessary instructions are added.
