### ISSUE TITLE
styled-components based extension inconsistencies (v3)

### ISSUE THREAD

**Issue by oomathias** [rebassjs/rebass#534]
Hi!

```js
// Navlink done right
const NavLink = styled(Link)`
  display: block;
`
NavLink.defaultProps = { color: 'inherit' }

<NavLink /> // => color: inherit
<NavLink color='red' /> // => color: red

// NavLink done wrong
const WrongNavLink = styled(Link)`
  color: yellow;
`
WrongNavLink.defaultProps = { display: 'block' }

<WrongNavLink /> // => color:blue (not yellow); display absent
// color:blue is a default prop on Link
// Link nor Box implement the display helper
```

Right now you have to look at the source or documention of rebass components to see if you should use CSS (display) or must use defaultProps (color on Link). Another example `fontWeight` usable on `Button` but not on `Link`.

What's the reason of not including `display` and the others `styled-system` relevent helpers in the rebass base components?

**Comment by jxnblk** [comment]
This is mostly the same API as before. Adding the entire set of CSS properties as component props is overkill IMO, and if you'd like to change less frequently used properties like `display`, you can extend the component with the `styled` HOC

**Comment by oomathias** [comment]
Actually, my problems were due to https://github.com/styled-components/styled-components/issues/2246 and are not related to `rebass` nor `styled-system`.

I'm closing ;)

**Comment by oomathias** [comment]
@jxnblk FYI that's probably something you don't want to happen with rebass, since all `defaultProps` defined in `rebass` are useless with the current state of `styled-components`. Unless you dont want to support styled-components based extension.

https://codesandbox.io/embed/wky9nlo1rw
