### ISSUE TITLE
Using ReactRouter Link and rebass Link together

### ISSUE THREAD

**Issue by mrcoles** [rebassjs/rebass#539]
Is there an elegant way to combine [React Router Link](https://reacttraining.com/react-router/web/api/Link) and [Rebass Link](https://rebassjs.org/Link)? I see I can just style the react-router one directly, but then I might be missing the theme and whatnot from Rebass.

**Comment by jxnblk** [comment]
You can use the `as` prop
```js
import { Link as RouterLink } from 'react-router'
import { Link as RebassLink } from 'rebass'

export default props =>
  <RebassLink
    {...props}
    as={RouterLink}
  />
```

**Comment by mrcoles** [comment]
Awesome, thanks!

**Comment by steverecio** [comment]
I only see this on dev but using the `as` keyword here is throwing an unknown prop warning from the `a` tag:

```
Warning: React does not recognize the `borderRadius` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `borderradius` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Comment by samburgers** [comment]
+1 Same issue as @steverecio
