### ISSUE TITLE
How to apply custom css with Rebass 3.0

### ISSUE THREAD

**Issue by mrfelton** [rebassjs/rebass#545]
As of version 3.0 I can no longer apply custom css using the `css` prop. It seems it was removed in #536 with some mention of this now being supported by `babel-plugin-styled-components` although no mention of how to use this and no reference to it in the documentation. The documentation at https://rebassjs.org/ still shows usage of the `css` prop with no mention of any special steps that need to be taken to get it to work.

What do I need to do so that I c an use `css` props with `v3.0.0` as I could with `v3.0.0-9`? Thanks.

**Comment by KingScooty** [comment]
From looking at the styled-components documentation, i assume you need to do this:

```js
<Box css={css`
  display: block;
`} />
```

**Comment by irishbryan** [comment]
Thanks for creating issue, thought I was going crazy. I personally got around the absence of the `css` prop by using `style` prop––although I'm not 100% if that is the best option.

Created this PR to update docs: https://github.com/rebassjs/rebassjs.org/pull/7

**Comment by mrfelton** [comment]
In theory, you should still be able to use `css` exactly as before when using `babel-plugin-styled-components`. However, it seems that are some bugs with it at the moment:

https://github.com/styled-components/babel-plugin-styled-components/issues/187
https://github.com/styled-components/babel-plugin-styled-components/issues/186

**Comment by mattrei** [comment]
works by just adding _babel-plugin-styled-components_ as a dependency and then update the [.babelrc](https://github.com/zeit/next.js/blob/master/examples/with-rebass/.babelrc)

**Comment by jxnblk** [comment]
From the official docs: https://www.styled-components.com/docs/api#css-prop

**Comment by mikedloss** [comment]
Just wanted to say this isn't working for me as well, on `rebass@3.0.1`, `babel-plugin-styled-components@1.10.0`, and `styled-components@4.1.3`. The `css` prop isn't being applied to `What`:

![unknown](https://user-images.githubusercontent.com/2460574/53247406-42265400-3681-11e9-9424-e09aa90420a1.png)

(it also doesn't work if I pass in a CSS object)

**Comment by justin-carlson** [comment]
Yep this tripped me up as well. Per the Rebass documentation for extending looks like you could use css={{prop: 'value'}} https://rebassjs.org/extending/

**Comment by aakhan89** [comment]
Using the css prop requires the use of babel-plugin-styled-components

**[https://www.styled-components.com/docs/api#css-prop](url)**

**Comment by mikedloss** [comment]
To be clear - even with `babel-plugin-styled-components`, it still didn't work. Somewhere in the toolchain of our project made the css prop not work at all.

**Comment by jxnblk** [comment]
@mikedloss would you mind opening a new issue to track that?

**Comment by mrfelton** [comment]
@mikedloss if you use the ‘as’ prop anywhere within your codebase, the css prop will break. See comments in https://github.com/rebassjs/rebass/issues/571
