### ISSUE TITLE
Unable to extending styling of Router Link

### ISSUE THREAD

**Issue by lunchboxav** [rebassjs/rebass#552]
Hi all,

I'm a new Rebass user, and I would like to know, how to extend styling of a React Router's Link. I've managed to combine both Rebass' and React Router's Link, but when I want to extend the styling of that component, like this

```
const StyledLink = props =>
  <RebassLink
    {...props}
    css={{
      display: 'block',
      textDecoration: 'none',
      color: 'green'
    }}
    as={RouterLink}
  />
```

Nothing is happening and upon inspection, the HTML is just rendered as `<a css=[Object object ...`

When I used the styled components method like this

```
const StyledLink = styled(RebassLink)({
  textDecoration: 'none',
  fontWeight: 'bold',
  display: 'block'
}) 

StyledLink.defaultProps = {
  color: 'green',
  as: 'RouterLink'
}
```

The visual appearance does change, but no HTML anchor element is rendered, instead, it would just be rendered as a div. 

Anybody know how to solve this? Thanks.

**Comment by jxnblk** [comment]
The first example looks like it *should* work, but it also looks like you *might* be missing babel-plugin-styled-components?? See: https://www.styled-components.com/docs/api#css-prop
