### ISSUE TITLE
Shouldn't the Text & Heading components be composed w/ the textStyle styled-system function? 

### ISSUE THREAD

**Issue by whatyoubendoing** [rebassjs/rebass#553]
Ie `<Text textStyle="body">` `<Text textStyle="caps">`  & `<Heading textStyle="page">`

**Comment by jxnblk** [comment]
Sorry, not sure I follow, but I see you've closed the issue...

**Comment by whatyoubendoing** [comment]
Sorry! Was a super brief description.  - I was wondering why the `<Text>` component wasnt composed with the `textStyle` function https://github.com/jxnblk/styled-system/blob/master/src/index.js#L603. But can see via 'pricelinelabs/design-systems' that there is a better approach for textStyles.
