### ISSUE TITLE
Give Text flex capabilities

### ISSUE THREAD

**Issue by vesparny** [rebassjs/rebass#554]
Hi there,

in rebass v2 the label component was something like

```js
import sys from '@rebass/components'

export const Label = sys({
  is: 'label',
  fontSize: 1,
  mb: 1,
  alignItems: 'center'
}, {
  display: 'flex'
},
  'alignItems',
  'fontSize',
  'space',
  'color'
)

Label.displayName = 'Label'
```

in order to migrate this component to v3 I should use a `Text` that also accepts `flex` specific props.
As of today `Text` inherits from `Box` but not from `Flex`.
What is the recommended way to do so?

**Comment by vesparny** [comment]
My understanding is that positioning should not be a concern of a Text components.
a Label is just for displaying text, so if it needs to be positioned, I can simply wrap it in a Flex component.

**Comment by jxnblk** [comment]
Yes, the idea is that Box and Flex are **layout** components, and Heading and Text are **typography** components. All of which can be composed together

**Comment by vesparny** [comment]
I see, thanks for the explanation
