### ISSUE TITLE
themed function in index.js 

### ISSUE THREAD

**Issue by imhuyqn** [rebassjs/rebass#556]
Can someone explain what does the themed function do? 

I found it in the source of Rebass but I don't quite understand what is its purpose.

Thank you!

**Comment by S1lentium** [comment]
I tested it and found that function needed for theming components manually. Like this:

```js
// theme.js
export default {
  Box: {
    backgroundColor: "#ccc",
  }
}
```
but in docs it is not described, also props "as" not described.

**Comment by imhuyqn** [comment]
Thank you for your response! I got it now. The props "as" is a feature from styled-components v4. You could find it [here](https://www.styled-components.com/docs/api#as-polymorphic-prop).
