### ISSUE TITLE
extend rebass components with other styled-system props

### ISSUE THREAD

**Issue by vesparny** [rebassjs/rebass#557]
Hi,

Trying to convert a `<Measure />` component from system-components to rebass 3.

This is what I came up with

```jsx
const Container = styled('div')(maxWidth)

export const Measure = ({ maxWidth, ...rest }) => {
  return (
    <Container maxWidth={maxWidth}>
      <Text {...rest} />
    </Container>
  )
}
``` 

I didn't find another way to do so.
doing so:
```jsx
const Measure = styled(Text)(maxWidth)
```

seems to wok but I didn't find a way to prevent the `maxWidth` attribute to end up on the dom node.

Is there any better way to avoid the intermediate component to wrap the Measure?

**Comment by lbineau** [comment]
@vesparny I think it is related to this issue https://github.com/rebassjs/grid/issues/85

**Comment by jxnblk** [comment]
Yes, this is a limitation of the Styled Components library. You can use Emotion to avoid unwanted HTML attributes, see https://styled-system.com/guides/removing-props-from-html
