### ISSUE TITLE
borders on boxes

### ISSUE THREAD

**Issue by agriffis** [rebassjs/rebass#559]
It seems like it would make sense to support borders on boxes, for example:

    <Box borderLeft={2} borderColor="green">

Right now borders only apply to buttons, images and cards. Would you accept a PR to add borders to boxes, or is there a reason you chose not to include them?

**Comment by jxnblk** [comment]
You should use the Card component or extend the Box to add visual styling. The Box is meant to be used purely for layout concerns (if that makes sense)

**Comment by agriffis** [comment]
Ah, I hadn't looked closely at what purpose Card filled. Makes sense, thanks.
