### ISSUE TITLE
Better debugging with babel-plugin-styled-components doesn't work

### ISSUE THREAD

**Issue by dapetrov** [rebassjs/rebass#560]
Hi, it seems that using this syntax of creating components causes better debugging with babel plugin not working.

export const Box = styled('div')({
    boxSizing: 'border-box'
},
    space,
    width,
    fontSize,
    color,
    flex,
    order,
    alignSelf,
    themed('Box')
)

If i change it to this (with tagged template literal) all is working fine.

const Box = styled('div')\`
  box-sizing: border-box;
    ${space}
    ${width}
    ${height}
    ${fontSize}
    ${color}
    ${flex}
    ${order}
    ${textAlign}
    ${alignSelf}
    ${display}
    ${props => props.theme.Box}
\`

Maybe I do something wrong... Thanks

**Comment by joserocha3** [comment]
I can confirm that this does work when using `css` prop as well.

**Comment by voordev** [comment]
any updates on this?

**Comment by peterp** [comment]
@dapetrov could you explain what the difference in the debugging experience is?

**Comment by jxnblk** [comment]
Sorry, I believe this is an issue with Styled Components' Babel plugin not correctly parsing the JS-syntax that Rebass uses, and I don't think there's much I can do about that
