### ISSUE TITLE
v2, v3  differences, docs

### ISSUE THREAD

**Issue by thm-design** [rebassjs/rebass#561]
Hi have a question about versions.

I see in the v2 docs (https://rebass-v2.now.sh/getting-started) there are a lot of components. In the main Rebass docs they are not listed. Were those other (non-primitve) components left out for v3.

Also I am using "@rebass/emotion": "^3.0.0" which components are/should be available there?

Sorry just a bit confused, love this library well done, and thanks very much for providing it.

**Comment by jxnblk** [comment]
See https://github.com/rebassjs/rebass/releases/tag/v3.0.0

`@rebass/emotion` should be a 1:1 replacement for `rebass` for when you'd prefer to use emotion instead of styled-components

**Comment by thm-design** [comment]
Perfect thanks! Feel free to close.
