### ISSUE TITLE
Typescript defintaion for flex prop of Box

### ISSUE THREAD

**Issue by S1lentium** [rebassjs/rebass#562]
Outdated types for BoxProps in @types/rebass

**Comment by chuckdries** [comment]
What should it be?

**Comment by macklinu** [comment]
I don't believe the types are maintained in this repo, but instead are maintained in the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped) (files are specifically located [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/rebass)).

**Comment by angusfretwell** [comment]
Hey @S1lentium this should be fixed now.
