### ISSUE TITLE
How to create Table in Rebass

### ISSUE THREAD

**Issue by aakhan89** [rebassjs/rebass#565]
Can anyone guide how to create Table in Rebassjs see below example..!

![image](https://user-images.githubusercontent.com/38126236/52532035-52b10300-2d40-11e9-9727-d099e1bed61b.png)

**Comment by jxnblk** [comment]
FWIW, you'll probably want to style your own since table styles tend to be fairly specific

**Comment by aakhan89** [comment]
> FWIW, you'll probably want to style your own since table styles tend to be fairly specific

Any example ?

**Comment by markgandy** [comment]
@aakhan89 I was searching for same thing, so just created very basic Table component without any styling:
```
import { Flex, Box, Text } from "rebass";

const Table = ({ columns, data }) => (
  <Box width={[1, 3 / 4, 2 / 3]}>
    <Flex flexWrap="wrap">
      {data.map((item, index) => {
        return (
          <Box px={2} width={1 / columns}>
            <Text
              p={1}
              style={{
                fontWeight: index < columns ? "bold" : "normal"
              }}
            >
              {item}
            </Text>
          </Box>
        );
      })}
    </Flex>
  </Box>
);

export default Table;
```

```
    <Table
      columns={4}
      data={[
        "Team",
        "Played",
        "Goal Diff",
        "Points",
        "Liverpool",
        "31",
        "+52",
        "76",
        "Man City",
        "30",
        "+58",
        "74"
      ]}
    />
```

**Comment by aakhan89** [comment]
@markgandy 

thanks for you reply and effort, I will look into this and let you know

**Comment by ratskin** [comment]
See my comment here https://github.com/rebassjs/rebass/issues/569#issuecomment-580388815
