### ISSUE TITLE
How to create Dropdown menu in rebass

### ISSUE THREAD

**Issue by aakhan89** [rebassjs/rebass#566]
How to create Dropdown menu in rebass

![image](https://user-images.githubusercontent.com/38126236/52532362-b25ddd00-2d45-11e9-8098-b2ae37f6b313.png)
![Uploading image.png…]()

**Comment by jxnblk** [comment]
You might want to look at Reach UI's dropdown: https://ui.reach.tech/menu-button

**Comment by aakhan89** [comment]
@jxnblk 
thank for your reply, is it suitable to use the third party library with Rebassjs & styled-component ?
as you mentioned above [](https://ui.reach.tech/menu-button)
