### ISSUE TITLE
Table Component Rebass V3

### ISSUE THREAD

**Issue by aakhan89** [rebassjs/rebass#569]
Can anyone create the Table component with RebassJs

see below example

![image](https://user-images.githubusercontent.com/38126236/52739460-cf6b0800-2ff2-11e9-99c1-a2485ce7c941.png)

**Comment by DuncanLewis** [comment]
Feel free to have a go yourself and submit a PR 👍

**Comment by aakhan89** [comment]
> 
> 
> Feel free to have a go yourself and submit a PR 👍

`<Flex flexWrap='wrap' mx={-2} >
                                <Box width={1/6}>
                                    <Text fontSize={[ 3, 4, 2 ]} lineHeight={2} p={2} color='#999' bg='#f9f9f9'>
                                       Column 1
                                    </Text>
                                </Box>
                                <Box width={5/6}>
                                    <Text fontSize={[ 3, 4, 2 ]} lineHeight={2} p={2} color='#333' bg='#f9f9f9'>
                                        Column 2
                                    </Text>
                                </Box>
                               </Flex>
`

here is code for now, will upgrade it if there is need, kindly have a look & advice

**Comment by jxnblk** [comment]
FWIW I don't plan on accepting PRs for composed components or anything for a `<table>` element, so I'd suggest publishing this on your own or keeping it in your application's codebase

**Comment by ratskin** [comment]
Why not just make components like this (typescript):

```
import React from 'react'
import { Box, BoxProps } from 'rebass'

/*
  Rebass doesn't support table elements yet.
  It comes with some default styling, that can be overridden in the usual ways (variant, sx, ...)
*/

export interface TableProps
  extends BoxProps,
    Omit<React.TableHTMLAttributes<HTMLTableElement>, keyof BoxProps> {}

export const Table: React.ComponentType<TableProps> = React.forwardRef((props, ref) => (
  <Box
    ref={ref}
    as="table"
    variant="table"
    {...props}
    sx={{ /* your default style goes here */ }}
  />
))

export interface TableBodyProps
  extends BoxProps,
    Omit<React.HTMLAttributes<HTMLTableSectionElement>, keyof BoxProps> {}

export const TableBody: React.ComponentType<TableBodyProps> = React.forwardRef((props, ref) => (
  <Box
    ref={ref}
    as="tbody"
    variant="tbody"
    {...props}
    sx={{ /* your default style goes here */ }}
  />
))

export interface TableRowProps
  extends BoxProps,
    Omit<React.HTMLAttributes<HTMLTableRowElement>, keyof BoxProps> {}

export const TableRow: React.ComponentType<TableRowProps> = React.forwardRef((props, ref) => (
  <Box
    ref={ref}
    as="tr"
    variant="tr"
    {...props}
    sx={{ /* your default style goes here */ }}
  />
))

export interface TableDataCellProps
  extends BoxProps,
    Omit<React.TdHTMLAttributes<HTMLTableDataCellElement>, keyof BoxProps> {}

export const TableDataCell: React.ComponentType<TableDataCellProps> = React.forwardRef(
  (props, ref) => (
    <Box
      ref={ref}
      as="td"
      variant="td"
      {...props}
      sx={{ /* your default style goes here */ }}
    />
  )
)
```
