### ISSUE TITLE
textDecoration property not working

### ISSUE THREAD

**Issue by aakhan89** [rebassjs/rebass#572]
@jxnblk 

Here is the codesandbox link where I extended the Link component with BlockLink and there is problem which css not working like textDecoration property not working

[https://codesandbox.io/s/wn5r67w73l](url)

**Comment by ntaylor89** [comment]
The codesandbox link doesn't work for me. What version of rebass / system-components are you using?

**Comment by jxnblk** [comment]
Not sure I 100% follow the issue here, but looks like you're missing `babel-plugin-styled-components` which is required for the `css` prop to work

**Comment by aakhan89** [comment]
> 
> 
> Not sure I 100% follow the issue here, but looks like you're missing `babel-plugin-styled-components` which is required for the `css` prop to work

The plugin call order in your `.babelrc` file matters.
`{
  "plugins": ["babel-plugin-styled-components"]
}`

`npm install --save-dev babel-plugin-styled-components`

I have installed the above, but didn't get `.babelrc` file in my project so where to add 

`{
  "plugins": ["babel-plugin-styled-components"]
}`

**Comment by aakhan89** [comment]
@jxnblk 

I got the file, thanks for your reply, I am going to close
