### ISSUE TITLE
Responsive Flexbox Ordering

### ISSUE THREAD

**Issue by steverecio** [rebassjs/rebass#573]
I have a flexbox and I would like to reverse its flex direction depending on the breakpoint. I'm trying to achieve the ordering as below:

Desktop view:

| 1 | 2 |
| 3 | 4 |
| 5 | 6 |

Mobile (notice how 3 and 4 switch):

| 1 |
| 2 |
| 4 |
| 3 |
| 5 |
| 6 |

**Comment by djordjevlais** [comment]
You can use `order` props with arrays to change the order of elements based on breakpoints.

```
<Box order={[3, 4]}>Element 4</Box>
<Box order={[4, 3]}>Element 3</Box>
```
https://rebassjs.org/Box#props

**Comment by steverecio** [comment]
@djordjevlais This is exactly what I needed. Thanks!
