### ISSUE TITLE
Extending Rebass Button component with styled-components renders <div>, not <button>

### ISSUE THREAD

**Issue by iaanvn** [rebassjs/rebass#574]
When extending the Button using the styled-components method, a `<div>` is rendered and not the expected `<button>`. It seems like my extended component is in fact extending the `<Box>` component and not the <Button> component since the default `<Button>` props from Rebass is also not applied to the extended `<Button>`.

**Example Button extension:**
```import styled from "styled-components";
import { Button as RebassButton } from "rebass";

export const Button = styled(RebassButton)`
  cursor: pointer;
`;

Button.defaultProps = {
  px: "10px"
};
```

**Rendering components using Storybook.js like this:**
```
import React from "react";
import { storiesOf } from "@storybook/react";
import { Button } from "./Button";
import { Button as RebassButton } from "rebass";

storiesOf("Components/Buttons", module).add("Button", () => (
  <div>
    <Button>Test Button</Button>
    <RebassButton>RebassButton</RebassButton>
  </div>
));
```

**Renders the following HTML:**
Expectation is obviously that the HTML and styling should be same, except for the `pointer: 10px`  and `cursor: pointer` (which is successfully applied to the extended `<Button>` component).
```
<div class="sc-bdVaJa sc-EHOje Button-sc-1hnn9eg-0 dAjgkL">Test Button</div>
<button font-size="inherit" font-weight="bold" color="white" class="sc-bdVaJa sc-EHOje fCPMYz">RebassButton</button>
```

**Example screenshot of result:**
<img width="268" alt="screenshot 2019-03-02 at 17 43 46" src="https://user-images.githubusercontent.com/10232052/53684176-d09a7580-3d12-11e9-8191-2586ff867a43.png">

**Details:**
```
"styled-components": "^4.1.3",
"styled-system": "^4.0.1",
"babel-plugin-styled-components": "^1.10.0",
```

_Using the same method when extending my own custom components with styled-components in a similar way as above does not result in the same issue._

**Comment by iaanvn** [comment]
Fix: I never actually created the component... Pasting this here for future reference. 
Complete component should be:
```
const Button = styled(RebassButton)`
  cursor: pointer;
`;

export const Button = ({ children, ...props }) => (
  <StyledButton {...props}>{children}</StyledButton>
);
```

instead of only this:
```
export const Button = styled(RebassButton)`
  cursor: pointer;
`;
```

**Comment by soavie** [comment]
I'm having the same issue that @iaanvn initially reported. I'm trying to extend the rebass `<Button>` component and add some `defaultProps`. As soon as I add `defaultProps`, the button gets converted to a `<div>`.

I tried the suggested fix, but that didn't work for me. I've created a [codesandbox] based on the example from this issue (https://codesandbox.io/embed/m5974q90rj).

**Comment by pbeshai** [comment]
I just ran into this and I think the solution is to include the default props from RebassButton e.g.,

```js
export const Button = styled(RebassButton)`
  cursor: pointer;
`;
Button.defaultProps = { ...RebassButton.defaultProps, yourProp: 'here' }
```
