### ISSUE TITLE
Certificate issue on https://rebassjs.org

### ISSUE THREAD

**Issue by mendelk** [rebassjs/rebass#575]
![image](https://user-images.githubusercontent.com/1313923/53859138-bed2ff80-3faa-11e9-92fb-1d5f37988529.png)

**Comment by aakhan89** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/1313923/53859138-bed2ff80-3faa-11e9-92fb-1d5f37988529.png)

facing same issue...!

**Comment by aakhan89** [comment]
![image](https://user-images.githubusercontent.com/38126236/53861631-7e08d400-4006-11e9-972a-34673ae31b78.png)

**Comment by aakhan89** [comment]
FYI... Working fine now.. issue should be closed now
Thanks

**Comment by mendelk** [comment]
Confirmed working!
