### ISSUE TITLE
Allow users to import from styled-components/macro to allow create-react-app users to use the css prop

### ISSUE THREAD

**Issue by gausie** [rebassjs/rebass#578]
For more information, see this https://medium.com/styled-components/css-prop-support-for-create-react-app-37e8c5d96861.

I'm not sure what happens if you import from `styled-components/macro` without babel-macros enabled. If it still works, we should simply switch to `styled-components/macro`. If not, it would be great to be able to import `rebass/macro` for the same effect.

**Comment by jxnblk** [comment]
Sorry for the delay, but instead of relying on the Babel plugin, v4 now supports the `css` prop without additional configuration again. I think this will resolve this issue, but feel free to reopen this if not
