### ISSUE TITLE
How to set bg color for even and odd rows

### ISSUE THREAD

**Issue by aakhan89** [rebassjs/rebass#579]
I am using box for row and column and want to set different bg color for even and odd rows..

Also I am rendering rows dynamically with map function

**Comment by corygibbons** [comment]
Can check if the index is even or odd and assign `bg` based on that.

**Comment by aakhan89** [comment]
@corygibbons 

I tried below, but not working fine, could you please look into this ? thanks

`let  num = 2;
    let data = props.TableData.map(each => { 
        if (num % 2 == 0) { 
            num++;
            return (
                <React.Fragment 
                    key={each.placeId}>
                    <Box
                        width={3 / 6}
                        bg='#f9f9f9'>
                        <Text
                            fontSize={[ 14 ]}
                            p={2}
                            color='#999'>
                            {each.text}
                        </Text>
                    </Box>
                    <Box width={3 / 6}
                        bg='#f9f9f9'>
                        <Text
                            fontSize={14}
                            p={2}
                            color='#333'>
                            {each.text}
                        </Text>
                    </Box>
                </React.Fragment>
            )
}
        
    })`

**Comment by aakhan89** [comment]
Done with if else, is there any other way which we can handle it for e.g

background: ${props => props.even? "mediumseagreen" : "#777"};
background: ${props => props.odd? "royalblue" : "#777"};

**Comment by corygibbons** [comment]
Same idea should apply, try this:

```js
const Styled = styled`
  background: ${props => props.isOdd? "red" : "blue"};
`;

things.map((item, i) => <Styled isOdd={Boolean(i%2)} />);
```

That will give you `red if it's odd, `blue` if it's even.

**Comment by puregarlic** [comment]
Personally, I'd do something like this:

```jsx
data.map((item, i) => <Box key={i} bg={i % 2 === 0 ? 'mediumseagreen' : 'royalblue'}>{item}</Box>
```

But it looks like you're using `styled-components` as well. In that case, I would do

```jsx
const Row = styled(Box)`
  background: ${props => props.index % 2 === 0 ? 'mediumseagreen' : 'royalblue'}
`

data.map((item, i) => <Row key={i} index={i}>{item}</Row>
```

If you wanted the table to have either alternating backgrounds or a single background, you could handle coloring these rows at the parent level. I think something like this would work:

```jsx
const Row = styled(Box)`
  /* some styles */
`

const Table = styled(Box)`
  ${props =>
    props.striped &&
    css`
      &:nth-child(event) {
        background: mediumseagreen;
      }

      &:nth-child(odd) {
        background: royalblue;
      }
    `}
`;

// somewhere else
return (
  <Table>
    {data.map((item) => <Row key={i}>{item}</Row>}
  </Table>
```

**Comment by aakhan89** [comment]
@corygibbons and @puregarlic 
you guys have done great job, thank you guys for provide multiple solution 👍
