### ISSUE TITLE
Add flexGrow prop to Box (suggestion)

### ISSUE THREAD

**Issue by gunar** [rebassjs/rebass#581]

**Comment by peterp** [comment]
@gunar  [rebass-extend](https://github.com/peterp/rebass-extend) might be helpful to you here.

**Comment by jxnblk** [comment]
Box includes the `flex` prop which is shorthand for `flex-grow` `flex-shrink` and `flex-basis`. You can also use the `css` prop for any other styles or extend the Box with `styled` and pass any additional styled-system functions you need to it

**Comment by gunar** [comment]
Right, it's just [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/flex#Syntax) at that point. Thank you @jxnblk.
