### ISSUE TITLE
Using Input component

### ISSUE THREAD

**Issue by azrijamil** [rebassjs/rebass#583]
I just wondering how to use Input component for Rebass, I try to import but the module doe not exist. It does exist on the earlier version.

Example:

`<Input name="email" label="Email" />`

**Comment by jxnblk** [comment]
Version 3 no longer includes an Input. You can either continue using v2, fork it, or follow the migration steps here https://github.com/rebassjs/rebass/releases/tag/v3.0.0

**Comment by azrijamil** [comment]
Ok, Thanks for the info. It seems using Reakit is the fastest solution for the replacement.

**Comment by aakhan89** [comment]
@azrijamil 

You ca have it by using styled Component see below example

```
import styled from 'styled-components';

const Input = styled.input`
    color: rgb(43, 45, 46);
    background-color: rgb(255, 255, 255);
    transition: all 0.2s ease 0s;
    border: 1px solid rgb(182, 184, 185);
    border-radius: 6px;
    border-style: solid;
    border-color: rgb(98, 100, 101);
    padding: 12px 16px;
    font-weight: 400;
    width: 90%;
`
```
