### ISSUE TITLE
Favicon for docs?

### ISSUE THREAD

**Issue by karlhorky** [rebassjs/rebass#584]
Hi, first of all, thanks for this project!

It would be nice to have a favicon to identify the tabs when no titles are shown (see screenshot below). It looks like the docs are being built with [`gx`](https://www.npmjs.com/package/gx), but I didn't see on first glance where a PR would be made for a favicon.

<img width="111" alt="Screen Shot 2019-04-09 at 11 00 30" src="https://user-images.githubusercontent.com/1935696/55787594-eab83800-5ab6-11e9-82ac-759eed38b9f7.png">

Maybe an option would be a monochrome / adapted version of the logo image?

<img width=250 src=https://camo.githubusercontent.com/4f6ca9438a3e45f9b409158503f3deebc86a793d/68747470733a2f2f7265626173736a732e6f72672f6c6f676f2e737667>

**Comment by jxnblk** [comment]
Sorry, i really don't care for favicons :p – if you find a simple way to add an npm script that takes the logo and creates a 32x32 png or `.ico` it can be output to the `static` directory here: https://github.com/rebassjs/rebassjs.org/tree/master/www/static – also peep how the `repng` cli is used for the icon

**Comment by karlhorky** [comment]
Cool, I'll do that then when I get a chance.

Do you have a vector non-animated version of the logo handy?

**Comment by jxnblk** [comment]
You should be able to generate one like here https://github.com/rebassjs/rebassjs.org/blob/master/www/package.json#L9-L11 with

```json
"static-svg": "scrs src/Icon.js --svg > static/icon.svg"
```

But lmk if that doesn't work

**Comment by karlhorky** [comment]
Ok this sounds like a plan. I took a look through the project (I've filed this issue in the wrong repo) and found the files that will be probably interesting to me.

I've documented these decisions in rebassjs/rebassjs.org#15. Closing this.

**Comment by karlhorky** [comment]
This was done in https://github.com/rebassjs/rebass/commit/1a46adb7fb184276dcf854b939ce1813ec3a9241
