### ISSUE TITLE
Not working with parcel-bundler's  --experimental-scope-hoisting option

### ISSUE THREAD

**Issue by midnightcodr** [rebassjs/rebass#586]
The source code is all here: https://gist.github.com/midnightcodr/fbcfc63ab80951b3f13b330b0ec1f406

Running the build command produces the `dist` directory without issues, however, when trying to access the http server based on `dist`, a blank page is rendered with the following error thrown in console:

<img width="596" alt="Screen Shot 2019-05-02 at 3 49 52 PM" src="https://user-images.githubusercontent.com/1152119/57103438-bd485e00-6cf3-11e9-8e3d-23f90ef078ba.png">

If I take out the `--experimental-scope-hoisting` option and build, page is rendered with content and no error is thrown in the console.

Please advise, Thanks.

**Comment by midnightcodr** [comment]
For comparison, If I use `styled-components` only, the build with or without the tree-shaking option works without issues.

See details at https://gist.github.com/midnightcodr/fbcfc63ab80951b3f13b330b0ec1f406/b143090313621abab1303d3b8f3c38c443c28101

**Comment by jxnblk** [comment]
Sorry for the delay! I don't use Parcel regularly, but it might be worth asking someone who can explain what `--experimental-scope-hoisting` does

**Comment by jxnblk** [comment]
Going to close this out for now. I'd recommend following up on the Parcel project if you haven't resolved this yet
