### ISSUE TITLE
Margin top does not appear when there's many flex

### ISSUE THREAD

**Issue by rayriffy** [rebassjs/rebass#587]
I trying to separate title away from Navbar by adding `mt` into `<Box />` from examples below

```
<Flex>
  // Box Navbar stuff here
</Flex>
<Flex>
  <Box mt={50}>
    <Heading>TITLE</Heading>
  </Box>
</Flex>
<Flex>
  // Another flex stuff
</Flex>
```

As the result margin-top is does not appear on production build

![](https://cdn.discordapp.com/attachments/378966019017801728/576453038823309356/unknown.png)

when digging into production build I noticed that CSS class that being rendered by Rebass is swapping all over the place

### Expectation

![](https://cdn.discordapp.com/attachments/378966019017801728/576454758798196759/unknown.png)

### Actual

![](https://cdn.discordapp.com/attachments/378966019017801728/576454664028028960/unknown.png)

Is this a bug on Flex system because I also tried injecting CSS directly into the `<Box />`

```
...
  <Box style={{marginTop: '50px'}}>
    <Heading>TITLE</Heading>
  </Box>
...
```

This is working fine as expected but this inject CSS won't appear unless you need to reload it for a second time.

PS. At first I think this is Gatsby issue but turns out it's not https://github.com/gatsbyjs/gatsby/issues/13966

**Comment by jxnblk** [comment]
Thanks! Sounds like this *might* be an issue with styled-components or emotion (depending on which version you're using). For use with something like Gatsby, be sure you have the correct plugin installed to handle static rendering, e.g. `gatsby-plugin-emotion`

**Comment by wiput1999** [comment]
@jxnblk I'm currently using Rebass with styled-component with the version I show you below.

```
"rebass": "^3.1.0",
"styled-components": "^4.2.0",
```

**Comment by rayriffy** [comment]
Yes, we're using Rebass based on styled-components and there's more wired when I playing around with Gatsby I will attach deploy previews below.

-   `gatsby-ssr` alone [Link](https://5cd6930a976d3300074c6d7f--thaiwithcodes-staging.netlify.com/)
-   `gatsby-broswer` alone [Link](https://5cd694566996f10007acfa7f--thaiwithcodes-staging.netlify.com/)
-   `gatsby-ssr` and `gatsby-browser` [Link](https://5cd5eb1dc1a0910008fc4f28--thaiwithcodes-staging.netlify.com/)
-   Nothing just directly add Layouts into each page [Link](https://5cd694ce0355e7000b4f3ecd--thaiwithcodes-staging.netlify.com/)

**Comment by jxnblk** [comment]
Do you have gatsby-plugin-styled-components in your Gatsby config?

**Comment by wiput1999** [comment]
@jxnblk Yes I've already installed and added to the config

**Comment by rayriffy** [comment]
No, the results are the same on second load

![](https://cdn.discordapp.com/attachments/567629588163854349/577026269221486592/unknown.png)

I have created PR in the repo here, you could checkout deploy preview by yourself https://github.com/wiput1999/thaiwith-codes/pull/5

**Comment by rayriffy** [comment]
Sorry for very late update, everything is seems fine now with no reason what caused it. I'll closed this issue for now until I encounter this issue again.
