### ISSUE TITLE
Extending with styled-system fails

### ISSUE THREAD

**Issue by nagyv** [rebassjs/rebass#593]
Hi,

I would like to create a variant on Card that is has all the flex properties too.

```
import styled from 'styled-components'
import { flexbox } from 'styled-system'
import { Card } from 'rebass`

const FlexCard = styled(Card)`
  ${flexbox}
`
```

It seems to me that the flexbox props are not applied to my FlexCard:

https://codesandbox.io/embed/sandboxv3-nrw5v

**Comment by jxnblk** [comment]
The latest version of Rebass uses `styled-system` v4 – I have a PR #591 to update the dependency, but you might have issues with two versions of the library installed at the same time

**Comment by JaKXz** [comment]
@nagyv does installing the latest `styled-system` work and not break any other components? :)

**Comment by jxnblk** [comment]
`v3.2.0` and up now uses Styled System v5
