### ISSUE TITLE
boxShadow from theme

### ISSUE THREAD

**Issue by JaKXz** [rebassjs/rebass#594]
Hi! huge fan of rebass, but I'm confused about the interaction between the styled-system ThemeProvider and rebass as it is currently documented, specifically regarding shadows.

I have my root element wrapped in a `ThemeProvider` that gets the following object in the `theme` prop:

```js
{
  //...
  fonts: {
    sans: "Proxima-Nova, Helvetica, Lato, Arial, Dropdown, sans-serif",
  },
  shadows: {
    small: "0 2px 4px -2px rgba(11, 39, 65, 0.3)",
  },
  //...
}
```

so I thought that would make this work, but it doesn't:

```jsx
<Box boxShadow="small">{children}</Box>
```

What am I doing wrong? Thanks in advance.

**Comment by jxnblk** [comment]
The Card component is a Box with visual style props like boxShadow, so you’d probably wanna use that one instead

**Comment by JaKXz** [comment]
Interesting, thanks. I think I understand the separation of concerns.

**Comment by cruzlutor** [comment]
I'm trying to use this solution but it doesn't work for me 
`<Card display="flex" boxShadow="small">`

The card element doesn't have a shadow, Am I missing something?

**Comment by haydnjm** [comment]
I'm also having trouble using the theme colours within `boxShadow`.

If my theme contains the following values:
`
{
  // ..
  colors: {
    background: 'white',
    shadow: 'green'
  },
  {
    blur: "0 0 50px 100px shadow",
  },
  {
    variants: {
      blurred: {
        boxShadow: "0 0 50px 100px shadow",
        backgroundColor: "background"
    }
  }
}
`

Then I cannot access the `shadow` theme colour through explicitly using `sx.boxShadow`, using the shadow theme, or using a variant with a shadow:
`
  <Box
    sx={{
      boxShadow: "0 0 50px 100px background"
    }}
  >
    Hello
  </Box>
`
`
  <Box
    sx={{
      boxShadow: "blur"
    }}
  >
    Hello
  </Box>
`
`
  <Box
    variant="blurred"
  >
    Hello
  </Box>
`

The other shadow props all work fine (blur radius/offset etc.) all work fine, but it doesn't seem to have access to the theme colours. In the case of the variant, the other props (`background`) also seem to get the theme colours fine. It's just when trying to use it with the shadow. It seems that you should be able to access the theme colours on all properties within the theme/using `sx`.

Am I missing something? Any help would be greatly appreciated 🙏 👍 

(using version `4.0.7`)

**Comment by austincollinpena** [comment]
No, it seems like a bug @cruzlutor
