### ISSUE TITLE
What happend to carousel?

### ISSUE THREAD

**Issue by yorickreum** [rebassjs/rebass#613]
Hi there!

First of all: Thanks for your amazing work!

At the moment, we are wondering how to create a carousel the right way with rebass? Is this still a feature / is there a component? Or any best practice? 

I can't find anything in the docs but in some older search results and in the changelog...

Kind regards from Würzburg!
Yorick

**Comment by jxnblk** [comment]
Sorry, but Rebass v3 does not include components like that at the moment, but I'm sure there are other React components out there you could use
