### ISSUE TITLE
Position props not working for @rebass/emotion

### ISSUE THREAD

**Issue by glockjt** [rebassjs/rebass#614]
I'm trying to style a prop as the following:

```js
<Box position="absolute" top="10" left="10">
  {/* inner content */}
</Box>
```

It's honoring the `position` prop but not `top` or `left`.  I noticed this working with styled-systems but not here.

**Comment by jxnblk** [comment]
The `Box` component intentionally does *not* include position props, you can extend it and add those props to a new component using Styled System

**Comment by glockjt** [comment]
Awesome thanks for the prompt response.  That's my fault for misinterpreting the docs.

**Comment by jxnblk** [comment]
No worries! The docs might not be super clear, so it's good to know where they need some work
