### ISSUE TITLE
Migration from v3 to v4

### ISSUE THREAD

**Issue by JaKXz** [rebassjs/rebass#629]
:wave: v4 looks really cool! 🙌  But NGL upon first read I'm a bit confused about some of the new packages and working with styled components and styled system and so on. 

As requested in the past on breaking changes, it would be cool to see some docs on what needs to change between v3 and v4 and even a breakdown of why v4 is better. I ask for the second thing because once I wrapped my head around the system concepts in v3 I felt super powerful so I think it'd help reinstate that feeling!

Also, ideally, it would be nice if the v3 docs could live on or be hosted somewhere? I understand if not, I'll just keep a fork.

Thanks!

**Comment by jxnblk** [comment]
Sorry, ran out of time putting all the notes together, here's a rough migration guide: https://rebassjs.org/migrating/

**Comment by jxnblk** [comment]
> Also, ideally, it would be nice if the v3 docs could live on or be hosted somewhere? I understand if not, I'll just keep a fork.

Yup, I'll be deploying a snapshot of v3 docs to netlify later for reference

**Comment by oquirozm** [comment]
@jxnblk hey there. Is TypeScript support for `reflexbox` module coming soon? Or is there a way to use the previous types from `@rebass/grid` with `reflexbox`?

**Comment by kimroen** [comment]
> @jxnblk hey there. Is TypeScript support for `reflexbox` module coming soon? Or is there a way to use the previous types from `@rebass/grid` with `reflexbox`?

@oquirozm The types on DefinitelyTyped didn't support importing from `rebass/styled-components` instead of the root either, so I created a type definition file (mine is called `rebass.d.ts`) with this in it to make the same types available at the other path:

```ts
declare module 'rebass/styled-components' {
  export * from 'rebass';
}
```

You could probably do something similar to make the `@rebass/grid` types available from `reflexbox`. Hope that helps!

**Comment by jxnblk** [comment]
v3 docs are now published to https://rebass-v3.now.sh – going to close this for now

**Comment by JaKXz** [comment]
@jxnblk have the `styled-system` exports been removed from v4?

**Comment by jxnblk** [comment]
@JaKXz Yes, you can import those from `styled-system` if you need them
