### ISSUE TITLE
TypeScript Support rebass v4?

### ISSUE THREAD

**Issue by kotarella1110** [rebassjs/rebass#635]
[@types/rebass](https://www.npmjs.com/package/@types/rebass) is supported rebass v3.
Are there any plans to update the type definition to support v4?

**Comment by martasko** [comment]
In the meantime, you can use this workaround
create `rebass.d.ts` with this content:

```
declare module 'rebass/styled-components' {
    import * as r from 'rebass';
    import { CSSObject } from 'styled-components';
    export interface BaseProps {
        sx?: CSSObject;
    }
    export = r;
}
```

**Comment by MaxSvargal** [comment]
@martasko it does not work with new props like maxWidth, overflow and others.

**Comment by orzarchi** [comment]
I've created a PR a few seconds ago in DefinitelyTyped, please take a look and see if I missed anything 🙏

**Comment by MaxSvargal** [comment]
> I've created a PR a few seconds ago in DefinitelyTyped, please take a look and see if I missed anything 🙏
> [DefinitelyTyped/DefinitelyTyped#37709](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37709)

Is there support for theme config variables checking? I don't see it...
For example:
```
export const Header = ({ transparent }: { transparent?: boolean }) => (
  <Box bg={['secondary', 'secondary', transparent ? 'transparent' : 'primary']} />
)
```
No validation of enum `secondary` and `primary` of theme.colors

**Comment by orzarchi** [comment]
No, I've only adapted the existing typings to work with v4, didn't add any features.

**Comment by MaxSvargal** [comment]
I understand, but it's not usable in production because there are no checking of theme.

**Comment by orzarchi** [comment]
It's merged! 🍾

**Comment by jxnblk** [comment]
Closing this since it sounds like the type definitions have been updated
