### ISSUE TITLE
Styled-System Scale Alias For Rebass

### ISSUE THREAD

**Issue by mirshko** [rebassjs/rebass#646]
Heya! 

Loving v4 so far ;) 

Just wondering if you're gonna support [Scale Aliases](https://styled-system.com/theme-specification/#scale-aliases) in Rebass? 

I presumed it would, but it seems rebass is not 100% styled-system which I was unawares of so its API is different.

**Comment by jxnblk** [comment]
Sorry I missed this earlier! You should be able to use any key (including aliases like that) in Rebass. If for some reason it's not working, please feel free to reopen this issue.
