### ISSUE TITLE
Can't override Button border color in a variant

### ISSUE THREAD

**Issue by orzarchi** [rebassjs/rebass#647]
It seems like there's a new default for `Button` in version 3: `border: 0`.
Since `border: 0` sets `border-color` to `initial`, it's impossible to override `border-color`, only `border`.

Here's an example:
```javascript
export const theme = {
    borderWidths: [0, 1, 2, 4],
    colors: {
        borderCommon: colors.steel,
        borderDialog: colors.silver,
    },
    buttons: {
        // impossible, overriden by default "border: 0"
        primary: {
            borderStyle: 'solid',
            borderColor: 'borderCommon',
            borderWidth: 3,
        },
        // possible, but awkward. renders "borderWidths" theme field pointless, unable to use color tokens
        dialog: {
            border: `solid 4px ${colors.silver}`,
        }
    },
};


```

**Comment by jxnblk** [comment]
Thanks! This shouldn't be the case, and I'm unable to reproduce locally. What version do you have installed and are you using the default Emotion or Styled Components version?

**Comment by orzarchi** [comment]
I'm using rebass 4.0.2, and using the styled components version.
I'll try to create a minimal reproduction

**Comment by jxnblk** [comment]
Just updated the sandbox in the README, have a look at this link and feel free to fork it to get a reproduction: https://codesandbox.io/embed/rebass-sandbox-lj3hb

**Comment by orzarchi** [comment]
I can't seem to reproduce the issue anymore, not sure what I did earlier.

**Comment by jxnblk** [comment]
No worries! Feel free to reopen this if you notice the bug again
