### ISSUE TITLE
Breaking change. Media query unitless breakpoint values.

### ISSUE THREAD

**Issue by JustinTRoss** [rebassjs/rebass#663]
Unitless breakpoint values now result in unitless media queries. Previously 'px' was added to the end.

`breakpoints: [840, 1050, 1280]`

I was able to resolve this by locking `@rebass/grid` version to `6.0`.

**Comment by JustinTRoss** [comment]
Probably related to https://github.com/styled-system/styled-system/issues/710

**Comment by jxnblk** [comment]
The `theme.breakpoints` scale has required units for a couple versions of Styled System now. The fact that it worked in Styled System v4 was accidental and not part of the public API

**Comment by JustinTRoss** [comment]
Nothing accidental about it:

```
export const px = n => (num(n) && n !== 0 ? n + 'px' : n)
export const createMediaQuery = n => `@media screen and (min-width: ${px(n)})
```

**Comment by JustinTRoss** [comment]
Regardless of Styled System design, it sounds like the forward intention with rebass is to not allow unitless breakpoint values. I'll make the necessary changes to upgrade to 6.1. Hopefully this issue will be helpful for anyone else in a similar situation.
