### ISSUE TITLE
Typescript error when extending component

### ISSUE THREAD

**Issue by andytan0727** [rebassjs/rebass#664]
I am extending component from `rebass`, basically `Text` component with some predefined styles, but then ended up with some TS error. Sample code demonstrating my words are as below:

```ts
import { Text, TextProps } from "rebass";

interface HighlightTextProps extends TextProps {
  text: string;
}

const HighlightText: React.FunctionComponent<HighlightTextProps> = (
  props: HighlightTextProps
) => {
  const { text, ...rest } = props;

  return (
    <Text
      {...rest}
      as="span"
      fontWeight="bold"
      py={1}
      px={1}
      sx={{
        backgroundColor: "highlight",
      }}
    >
      {text}
    </Text>
  );
};
````

Then, `Text` component wrapped inside `HighlightText` is showing error:

![rebass](https://user-images.githubusercontent.com/27825916/63651143-7390f100-c784-11e9-854b-c3beed553d9e.jpg)

If I am not mistaken, the main problem should be the `css` props. When I omit it from either `TextProps` or directly from `@types/rebass` own .d.ts file, the error gone.

Some further information of related packages on my machine:
```
OS: Windows 10
Typescript: v3.5.2
rebass: v4.0.5
@types/rebass: v4.0.0
```

**Comment by kimroen** [comment]
Hi! This sounds like an incompatibility problem between the `css` prop defined in the `@types/rebass` types and the one you have set up for emotion.

Could you share more about how you have set up support for the `css` prop with emotion?

**Comment by andytan0727** [comment]
Sure. I am using `rebass` + `ThemeProvider` from `theme-ui` in a `gatsby` project, with a custom `theme` that extends `@theme-ui/presets`. Below are more information for my project:

`tsconfig.json`
```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "baseUrl": ".",
    "paths": {
      "@src/*": [
        "src/*"
      ],
      "@components/*": [
        "src/components/*"
      ]
    },
    "jsx": "preserve",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "module": "esnext",
    "noImplicitAny": true,
    "outDir": "./dist/",
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "esnext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "typeRoots": [
    "./node_modules/@types",
    "./typings"
  ],
  "include": [
    "./src/**/*"
  ],
  "exclude": [
    "node_modules",
    "static",
    "public",
    "test",
    "./vscode",
    "./.cache"
  ]
}
```

Full details of my project dependencies in `package.json`
```json
{
  "dependencies": {
    "@emotion/core": "^10.0.16",
    "@mdx-js/react": "^1.3.1",
    "@theme-ui/presets": "^0.2.34",
    "@types/node": "^12.7.2",
    "@types/react": "^16.9.2",
    "@types/react-dom": "^16.9.0",
    "@types/react-helmet": "^5.0.9",
    "@types/react-scroll": "^1.5.4",
    "@types/rebass": "^4.0.0",
    "@types/theme-ui": "^0.2.2",
    "classnames": "^2.2.6",
    "gatsby": "^2.13.75",
    "gatsby-image": "^2.2.11",
    "gatsby-plugin-manifest": "^2.2.8",
    "gatsby-plugin-offline": "^2.2.9",
    "gatsby-plugin-react-helmet": "^3.1.4",
    "gatsby-plugin-sharp": "^2.2.15",
    "gatsby-plugin-theme-ui": "^0.2.34",
    "gatsby-plugin-typescript": "^2.1.3",
    "gatsby-source-filesystem": "^2.1.13",
    "gatsby-transformer-remark": "^2.6.17",
    "gatsby-transformer-sharp": "^2.2.9",
    "normalize.css": "^8.0.1",
    "prop-types": "^15.7.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-helmet": "^5.2.1",
    "react-icons": "^3.7.0",
    "react-scroll": "^1.7.13",
    "react-spring": "^8.0.27",
    "rebass": "^4.0.5",
    "theme-ui": "^0.2.36",
    "typescript": "^3.5.3"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.0.0",
    "@typescript-eslint/parser": "^2.0.0",
    "env-cmd": "^9.0.3",
    "eslint": "^6.2.1",
    "eslint-config-prettier": "^6.1.0",
    "eslint-config-react": "^1.1.7",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^2.0.1",
    "husky": "^3.0.4",
    "lint-staged": "^9.2.3",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.18.2",
    "rimraf": "^3.0.0"
  },
}
```

For module augmentation, I am only doing simple augmentation for `@theme-ui/presets` as it has no definition file available yet. I am not touching either `emotion`, `react` or `JSX`. With that said, I somewhat sure that I haven't touch `css` prop anywhere except using what is being provided.

`global.d.ts`
```ts
type Colors = {
  text: string;
  background: string;
  primary: string;
  secondary: string;
  highlight: string;
  purple: string;
  muted: string;
  gray: string;
};

declare module "@theme-ui/presets" {
  export const deep: {
    styles: {};
    colors: Colors;
  };

  export const swiss: {
    styles: {};
    colors: Colors;
  };
}
```

@kimroen to answer your question, I could not think what I have set up support for `css` prop with emotion in my project. I think I have not touch anything related to `css` prop, or maybe I missed it somewhere?

Regards.

**Comment by thebuilder** [comment]
Looking at the `@types/rebass`, the problem is that it defines the `css` value in the `BaseProps` using `styled-components`, instead of `emotion`.

It can be fixed by adding `CSSObject` from `@emotion/serialize` to the `BaseProps`.
The types should be updated to allow this - especially seeing how Emotion is the default css framework

**Comment by andytan0727** [comment]
Thanks @thebuilder. After trying your solution locally without waiting `@types/rebass` updated, the problem still exists. Then I manage to get some time playing with `DefinitelyTyped` today, figured out that the problem is not coming from `@types/rebass`, but from the global `JSX` augmentation in `@emotion/core`.

In `DefinitelyTyped`, `rebass-tests.tsx` with unchanged `index.d.ts`:
```tsx
interface ExtendedTextProps extends TextProps {
    text: string;
}

const ExtendedText: React.FunctionComponent<ExtendedTextProps> = (props: ExtendedTextProps) => {
    const { text, ...rest } = props;

    return (
        <Text
            {...rest}
            as="span"
            fontWeight="bold"
            py={1}
            px={1}
            sx={{
                backgroundColor: 'highlight',
            }}
        >
            {text}
        </Text>
    );
};

export default () => (
    <Box width={1} css={{ height: '100vh' }} py={[1, 2, 3]} ml="1em">
        <Flex width={1} alignItems="center" justifyContent="center">
            ...
            <ExtendedText text="sample" />

        </Flex>
    </Box>
)
```
Running `npm run lint rebass` gives me no error.

Then, below is the mentioned `JSX` augmentation from `@emotion/core`:
```ts
declare global {
  namespace JSX {
    ...

    interface IntrinsicAttributes {
      css?: InterpolationWithTheme<any>  // <- here
    }
  }
}
```

To support that, I removed my global styles applied with `Global` from `@emotion/core`:
```ts
import { css, Global } from "@emotion/core";

const GlobalStyles = () => {
  return (
    <Global
      styles={css`some global styles...`}
    />
  );
};
```
After removing imports from `@emotion/core` and `GlobalStyles`, the error is gone. With some further experimenting, I find that the problem will arise whenever the `@emotion/core` is imported.

Since the problem is due to me applying global styles with `@emotion/core` and it's not related to `rebass`, I think perhaps I should close this issue.
