### ISSUE TITLE
Unable to use theme colours for certain theme variant props

### ISSUE THREAD

**Issue by mrfelton** [rebassjs/rebass#694]
Unable to use theme colours for certain theme variant props. Specifically, using a theme colour in `color` to set the input text color works as expected, but using a theme colour in `caretColor` does not work

eg:

```js
forms {
  input: {
    normal: {
      color: 'primaryText'
      caretColor: 'primaryAccent',
      lineHeight: 'normal',
      px: 3,
      height: 80,
      fontSize: 'l',
    },
  },
}
```

Note, it works fine if I pass a raw hex colour code, like `caretColor: '#fd9800'`.

**Comment by jxnblk** [comment]
Only certain CSS properties are mapped to the theme scales by default, and `caret-color` is not one of them. You can use a function as a value to work around this, e.g. `caretColor: t => t.colors.primaryAccent`

**Comment by mrfelton** [comment]
Can functions be used like that in theme variant definitions?

**Comment by jxnblk** [comment]
It should work, yes.

**Comment by mrfelton** [comment]
Confirmed, thanks!
