### ISSUE TITLE
Styling child Box doesn't work anymore

### ISSUE THREAD

**Issue by publicJorn** [rebassjs/rebass#695]
I'm working on a project where the `@rebass/grid` package was used. Now I want to upgrade.

They used this css, but after the upgrade it results in an error: `Maximum call stack size exceeded`.

```js
import styled, { css } from 'styled-components'
import { Box } from 'reflexbox'

const Row = styled.div`
    flex: 1 1 auto;
    display: flex;
    flex-wrap: wrap;
    margin-left: -${(p) => p.gutter / 2}px;
    margin-right: -${(p) => p.gutter / 2}px;

    > ${Box} {  /* <-- this is the culprit */
        padding-left: ${(p) => p.gutter / 2}px;
        padding-right: ${(p) => p.gutter / 2}px;
    }
`

export default Row
```

> This component is used in conjunction with a `<Col>` component which also exports an instance of `<Box>`.

I'm not sure what the difference is between the old and new `Box`.  
Any idea how can I work around this?

**Comment by publicJorn** [comment]
Ouch... found the answer at the bottom of the docs: https://rebassjs.org/reflexbox#styled-components

```js
import { Box } from 'reflexbox/styled-components'
```

Styling is broken, but at least no error!

**Comment by jxnblk** [comment]
Could you create a reproduction on CodeSandbox? This sounds like a weird issue with styled-components

**Comment by publicJorn** [comment]
Right, I guess I made a bit of a mess of it.. In order to complete this issue I created a [sandbox](https://codesandbox.io/s/reflexbox-styling-box-50pjg). But there it works as expected.

For the project I'm now working on I realised they only use the Box component with 2 extentions (Row and Col). So I just created my own components, which saves us a dependency.

Sorry to bother @jxnblk!
