### ISSUE TITLE
Attempted import error: 'Provider' is not exported from 'rebass'.

### ISSUE THREAD

**Issue by MrBandaruk** [rebassjs/rebass#697]
I've use `create-react-app` to init my app. Then I added `react-landing-page` and `rebase`. Here is my App.js code:

```javascript
import React from 'react'
import { Provider, Heading, Subhead } from 'rebass'
import {
  Hero, CallToAction, ScrollDownIndicator
} from 'react-landing-page'

const App = props => (
  <Provider>
    <Hero
      color="black"
      bg="white"
      backgroundImage="https://source.unsplash.com/jxaj-UrzQbc/1600x900"
    >
        <Heading>Name of your app</Heading>
        <Subhead>a couple more words</Subhead>
        <CallToAction href="/getting-started" mt={3}>Get Started</CallToAction>
        <ScrollDownIndicator/>
    </Hero>
  </Provider>
)

export default App;
```

I get this error:
`Attempted import error: 'Provider' is not exported from 'rebass'.`

**Comment by jxnblk** [comment]
Rebass doesn't have a `Provider` component - perhaps you're looking at an older version of the docs?

**Comment by MrBandaruk** [comment]
Oh, thank you. My bad

**Comment by moyid** [comment]
@n3nikita - I'm running into the exact same issue. (This is the code for https://hermanya.github.io/react-landing-page/getting-started/, if I'm not mistaken). How did you fix this? Is there an updated equivalent to Provider?

**Comment by n3nikita** [comment]
@moyid No. They don't have updates for react-landing-page and code is outdated
