### ISSUE TITLE
'sx' prop inconsistency

### ISSUE THREAD

**Issue by neist** [rebassjs/rebass#698]
Hi

Love your work!

I'm using `reflexbox`for a project and i noticed this inconsistency:

```js
<Box sx={{ width: [1, 1/2] }}/>
```
This results in `width: 1px` and `width: 0.5px`

```
<Box width={[1, 1/2]}/>
```
This results in `width: 100%` and `width: 50%`

Shouldn't they behave the same?

**Comment by jxnblk** [comment]
The fractional width values do not work with the `sx` prop, only in the `width` prop. We decided not to add that shorthand to the `@styled-system/css` package since it's a little lesser known and non-standard
