### ISSUE TITLE
Render HTML props inline when extends with styled-component and "as" prop works incorrectly

### ISSUE THREAD

**Issue by MaxSvargal** [rebassjs/rebass#699]
When I trying to extend any rebass component with style-components `styled` it renders some props inline. For example:

```
import { Text } from 'rebass/styled-components'
import styled from 'styled-components'

const LightWeightText = styled(Text)(({ theme }) => ({
  fontFamily: theme.font.light,
}))

const Component = () => (
            <LightWeightText fontSize={[28, 28, 44]} lineHeight='2' wontWeight="300">
              ...
            </LightWeightText>
)
```

Output:
```<div font-size="24,24,44" class="sc-jlyJG jSrArg sc-bdVaJa cBoHyH" font-weight="300">...</div>```

**And bonus!**
If try to use `as` prop then styled-components stop working and doesn't generate classes for element.

`styled-components 4.3.2`
`rebass 4.0.5`

**Comment by jxnblk** [comment]
This is a long-standing issue with Styled Components, see https://github.com/styled-components/styled-components/issues/439

You can use the `sx` prop to avoid this. As far as the `as` prop goes, I'm not sure what would cause that, but might be worth opening an issue on the Styled Components repo

**Comment by MaxSvargal** [comment]
@jxnblk `sx` and `style` props doesn't work with `as` prop.

**Comment by jxnblk** [comment]
I'm unable to reproduce your issue, and I'd recommend using the Emotion version if possible. If you have a reproduction of this issue, feel free to link to it and reopen
