### ISSUE TITLE
Font flickering when use local fonts

### ISSUE THREAD

**Issue by afnizarnur** [rebassjs/rebass#700]
Hi, anyone can help me to solve font flickering when use local fonts? Below what I meant:

![Kapture 2019-09-07 at 16 00 10](https://user-images.githubusercontent.com/4648648/64472436-94941180-d188-11e9-84cb-eda8585d0949.gif)

I already inject the font-family definition on GlobalStyles based on #595 , #294.
```
const GlobalStyles = createGlobalStyle`
  body {
    font-family: "Inter", sans-serif!important;
  }
```

**Comment by jxnblk** [comment]
Without more details it's hard to know what's happening here. If you're using Gatsby, make sure you have `gatsby-plugin-styled-components` installed for SSR

**Comment by afnizarnur** [comment]
Thank you for your reply @jxnblk 
Yes, I'm using Gatsby. It's solved now by importing the CSS file of the fonts in the layout wrapper. 

```
import React from "react"
import PropTypes from "prop-types"
import Helmet from "react-helmet"
import { createGlobalStyle, withTheme } from "styled-components"
import { useSiteMetadata } from "../utils/hooks"
import "sanitize.css"
import "./fonts/inter.css"
```
