### ISSUE TITLE
Responsive Styles Not Working

### ISSUE THREAD

**Issue by BarnabasChun** [rebassjs/rebass#701]
This issue occurred prior to attempting to migrate to v4 using v3.1.1 midway through working on the project (sorry can't provide much insight into why) and I thought updating to v4 would help. It did initially as the responsive styles applied but then the styles were not reading from the theme file.

Since the project I'm working with uses styled components I did as per the docs and changed references to 'rebass/styled-components' instead of 'rebass', which then succesfully allowed styles to read from the theme. But now the the responsive styles available through the array syntax no longer apply. 

Code sandbox reproduction with v4: https://codesandbox.io/s/rebass-and-styled-components-v4-y3zdm

Seems to happen in any version after v3.1.x: https://codesandbox.io/s/rebass-and-styled-components-v4-bvml5

**Comment by jxnblk** [comment]
It looks like the `theme.breakpoints` array is missing the unit. The values in the array need to include CSS units to work correctly, e.g. (`breakpoints: [ '40em', '52em']`) This was a change from v3 to v4

**Comment by BarnabasChun** [comment]
yup that was it - thanks!
