### ISSUE TITLE
4.0.x breaks wrapped style props

### ISSUE THREAD

**Issue by johnryan** [rebassjs/rebass#718]
When wrapping a component in 4.0 it appears that the props are no longer passed to the rebass components.

Here's an example with 3.x: https://codesandbox.io/s/affectionate-golick-0lio2

You can see that the `color` prop gets passed down to the rebass text and gets colored red

However in 4.x: https://codesandbox.io/s/lucid-cartwright-vdrbx

The extended component loses the `color` prop (with both emotion and styled-components)

**Comment by jxnblk** [comment]
Looks like the links you provided might not be the right ones. Could you double check that you've saved the sandbox examples?

**Comment by johnryan** [comment]
@jxnblk sorry about that, hadn't saved the sandbox, should be linked properly now

**Comment by jxnblk** [comment]
It looks like it's working with Emotion (https://codesandbox.io/s/dazzling-austin-tlqzl) - but you were using `styled-components` to extend the component. This looks like a bug with `styled-components` though: https://codesandbox.io/s/peaceful-cohen-fkfgj and it might be worth opening an issue on their repo

**Comment by johnryan** [comment]
@jxnblk Got it, do you have any ideas why this works in 3.x but not 4.x? styled-components version is the same in both

**Comment by jxnblk** [comment]
The Reflexbox and Rebass components are all created with the `styled` HOC, so it's a little different than passing the `className` prop through, and it *should* work – I'm really not sure why it wouldn't work as far as the styled-components API goes

**Comment by johnryan** [comment]
@jxnblk okay i'll do some digging and see if I can figure it out. If I find the issue i'll open a PR. Thanks for responding so quickly!

**Comment by johnryan** [comment]
I think you're right about the `as` issue (it works fine if i don't use that). I set up a trimmed down example here: https://codesandbox.io/s/optimistic-mcnulty-ki61b

but it looks like it basically comes down to how the `Text` component is built..

namely:
`const Text = forwardRef((props, ref) => <Box ref={ref} tx="text" {...props} />);`
vs
`const Text = styled(Box)(themed("Text"));`

**Comment by johnryan** [comment]
I reworked to use the `sx` and `css` props where appropriate ant it seems to solve the issue. Going to close this since it seems like a fine workaround. Thanks again!
