### ISSUE TITLE
Need some help! I'm confused with fonts

### ISSUE THREAD

**Issue by talentlessguy** [rebassjs/rebass#722]
I've set a font for body in my theme.js but `body`'s font is still default one (serif). How can I fix that?

Theme usage:

```jsx
      <Fragment>
        <GlobalStyle />
        <Meta />
        <ApolloProvider client={apollo}>
          <ThemeProvider theme={theme}>
            <Component {...pageProps} />
          </ThemeProvider>
        </ApolloProvider>
      </Fragment>
```

theme.js:

```js
export default {
  fonts: {
    body: '"Source Sans Pro", "Segoe UI", sans-serif',
    monospace: '"Fira Code", monospace',
    heading: 'inherit'
  },
  buttons: {
    primary: {
      background: 'black',
      color: 'white'
    },
    secondary: {
      color: 'white',
      background: 'blue'
    }
  },
  fontSizes: [12, 16, 20, 24, 'calc(1.8em + 2vw)', 'calc(3em + 5vw)']
}
```

![image](https://user-images.githubusercontent.com/35937217/64966508-90ae7080-d8a7-11e9-8a46-fdf44d3863cc.png)

there should be `"Source Sans Pro", "Segoe UI", sans-serif` but it is empty instead

**Comment by jxnblk** [comment]
You'll need to specify the font in a style somewhere – e.g. with a wrapping Box component:

```jsx
<Box
  sx={{
    fontFamily: 'body',
  }}
/>
```

**Comment by talentlessguy** [comment]
@jxnblk

thanks for response! things are clear now

so it is not possible to setup "base" font for body tag, right?
