### ISSUE TITLE
Rebass V4 is not compatible with Styled components

### ISSUE THREAD

**Issue by Kalpana-Nagan** [rebassjs/rebass#723]
I am trying to apply styles to styled Button and Button I have used from rebass/styled-components, I am unable to apply styles to styled button.

versions I have used:
 "styled-components": "^4.3.2",
 "rebass": "^4.0.5",

here is my code:

```
import { Button } from 'rebass/styled-components';
import { string, number, oneOfType, arrayOf, node, func } from 'prop-types';
import styled from 'styled-components';

 const StyledButton = styled(Button)`
  cursor: pointer;
`; 

const BaseButton = ({
  children,
  type,
  variant,
  width,
}) => (
  <StyledButton
    variant={variant}
    type={type}
    width={width}
>
    {children}
  </StyledButton>
);

```

**Comment by jxnblk** [comment]
It looks like the code example you have *should* work, but generally I'd recommend using the `sx` prop to extend Rebass components as seen here: https://rebassjs.org/extending

If you can provide a reproduction on code sandbox, that can be helpful for debugging
