### ISSUE TITLE
 Set border radius for buttons in theme.js?

### ISSUE THREAD

**Issue by talentlessguy** [rebassjs/rebass#724]
Sorry for making so many issues, I just couldn't find this in docs.

How do I set border radius for buttons?

I know how to set border for a variant.

```js
buttons: {
    primary: {
      background: 'black',
      color: 'white',
      borderRadius: 40
    },
    secondary: {
      color: 'white',
      background: 'blue'
    }
  }
```
But I use the same border raidus everywhere. Is there any way to make all buttons have the same border?

I tried this:

```js
  radii: {
    buttons: 48
  }
```

And this:

```js
buttons: {
    borderRadius: 20,
    primary: {
      background: 'black',
      color: 'white'
    },
    secondary: {
      color: 'white',
      background: 'blue'
    }
  },
```

both don't work

**Comment by jxnblk** [comment]
No worries! The docs probably aren't very clear about this at the moment. While there isn't a notion of a "base" button variant, you can add a border radius to the `primary` variant and extend that variant in other variants, e.g.:

```js
buttons: {
    primary: {
      background: 'black',
      color: 'white',
      borderRadius: 40
    },
    secondary: {
      variant: 'buttons.primary',
      color: 'white',
      background: 'blue'
    }
}
```

**Comment by talentlessguy** [comment]
> No worries! The docs probably aren't very clear about this at the moment. While there isn't a notion of a "base" button variant, you can add a border radius to the `primary` variant and extend that variant in other variants, e.g.:
> 
> ```js
> buttons: {
>     primary: {
>       background: 'black',
>       color: 'white',
>       borderRadius: 40
>     },
>     secondary: {
>       variant: 'buttons.primary',
>       color: 'white',
>       background: 'blue'
>     }
> }
> ```

So it is not possible to add same border radius everywhere? Then I'll try to use extending via styled-components.

Thanks for response (again). Is it planned to add "base" properties for variants? I can try to make a PR with this stuff I have enough power :smile:

**Comment by jxnblk** [comment]
Forgot to mention: you can also define `theme.radii` then use values from that scale in your button variants.

> So it is not possible to add same border radius everywhere?

Not sure I understand what you mean??

**Comment by talentlessguy** [comment]
@jxnblk I meant this:

```js
buttons: {
    borderRadius: 20,
    ...
```

Also thanks about mentioning `theme.radii` but is documented nowhere

**Comment by jxnblk** [comment]
See these for more about theming
- https://rebassjs.org/theming
- https://theme-ui.com/theme-spec/
- https://styled-system.com/theme-specification

**Comment by talentlessguy** [comment]
@jxnblk 

tried this:

```js
export default {
  fonts: {
    body: '"Source Sans Pro", "Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    monospace: '"Fira Code", monospace',
    heading: 'inherit'
  },
  buttons: {
    borderRadius: 20,
    primary: {
      background: 'black',
      color: 'white'
    },
    secondary: {
      color: 'white',
      background: 'blue'
    }
  },
  fontSizes: [12, 16, 20, 24, 'calc(1.8em + 2vw)', 'calc(3em + 5vw)'],
  space: [0, 4, 8, 14, 24, 36],
  radii: 28
}

```

and this

```js
export default {
  fonts: {
    body: '"Source Sans Pro", "Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    monospace: '"Fira Code", monospace',
    heading: 'inherit'
  },
  buttons: {
    borderRadius: 20,
    primary: {
      background: 'black',
      color: 'white'
    },
    secondary: {
      color: 'white',
      background: 'blue'
    }
  },
  fontSizes: [12, 16, 20, 24, 'calc(1.8em + 2vw)', 'calc(3em + 5vw)'],
  space: [0, 4, 8, 14, 24, 36],
  radii: [20]
}
```

and this:

```js
export default {
  fonts: {
    body: '"Source Sans Pro", "Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    monospace: '"Fira Code", monospace',
    heading: 'inherit'
  },
  buttons: {
    borderRadius: 20,
    primary: {
      background: 'black',
      color: 'white'
    },
    secondary: {
      color: 'white',
      background: 'blue'
    }
  },
  fontSizes: [12, 16, 20, 24, 'calc(1.8em + 2vw)', 'calc(3em + 5vw)'],
  space: [0, 4, 8, 14, 24, 36],
  radii: {
    buttons: 48,
    default: 48,
    variants: 48
  }
}
```

none of them work. I've read Theme Spec and Styled System, no any examples with `radii`

![image](https://user-images.githubusercontent.com/35937217/65044038-d4b37b00-d964-11e9-984f-719324bc1912.png)

![image](https://user-images.githubusercontent.com/35937217/65044048-dbda8900-d964-11e9-9938-2f68815b3fb4.png)

Would be cool to see a demo with all the buttons using same `radii`

**Comment by jxnblk** [comment]
`buttons.borderRadius` is *not* part of the spec -- not sure where you saw that -- the docs use the same radius for all buttons if you want to see how that is done

**Comment by talentlessguy** [comment]
> `buttons.borderRadius` is _not_ part of the spec

Uh sorry this is not the code I wanted you to see. I meant I tried this:

```js
radii: 28
```

this:

```js
radii: [20]
```

and this:

```js
  radii: {
    buttons: 48,
    default: 48,
    variants: 48
  }
```

In other words, I still don't understand how to set buttons' radius using `theme.radii` :(

>  the docs use the same radius for all buttons if you want to see how that is done

So it is possible to change default border radius from `theme.js`?

**Comment by jxnblk** [comment]
The following adds a `radii` scale that is used in the `buttons` variants
```
{
  radii: { 
    small: 2,
    large: 6,
  },        
  buttons: {      
    primary: {        
      borderRadius: 'small',
    },                          
    secondary: {                    
      variant: 'buttons.primary',     
    },                                
  },
}
```

**Comment by talentlessguy** [comment]
@jxnblk okay, so it seems that there is no way to make universal border radius...

I don't understand why but your solution doesn't work...

```js
export default {
  fonts: {
    body: '"Source Sans Pro", "Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    monospace: '"Fira Code", monospace',
    heading: 'inherit'
  },
  radii: {
    small: 10,
    large: 40
  },
  buttons: {
    primary: {
      background: 'black',
      color: 'white',
      borderRadius: 'large'
    },
    secondary: {
      color: 'white',
      background: 'blue',
      borderRadius: 'buttons.primary'
    }
  },
  fontSizes: [12, 16, 20, 24, 'calc(1.8em + 2vw)', 'calc(3em + 5vw)'],
  space: [0, 4, 8, 14, 24, 36]
}
```

Default still:

![image](https://user-images.githubusercontent.com/35937217/65059742-38e33880-d97f-11e9-8bdd-af2c0b2a54d3.png)

```js
export default {
  fonts: {
    body: '"Source Sans Pro", "Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    monospace: '"Fira Code", monospace',
    heading: 'inherit'
  },
  radii: {
    small: 10,
    large: 40
  },
  buttons: {
    primary: {
      background: 'black',
      color: 'white',
      borderRadius: 40
    },
    secondary: {
      color: 'white',
      background: 'blue',
      borderRadius: 'buttons.primary'
    }
  },
  fontSizes: [12, 16, 20, 24, 'calc(1.8em + 2vw)', 'calc(3em + 5vw)'],
  space: [0, 4, 8, 14, 24, 36]
}
```

But when I set numbers, not using `theme.radii`, it works but only with the one that has borderRadius with a number. Is it expected behaviour?



![image](https://user-images.githubusercontent.com/35937217/65059857-67611380-d97f-11e9-8c06-99856eecf378.png)

**Comment by jxnblk** [comment]
You're missing the `variant` on `buttons.secondary`

**Comment by talentlessguy** [comment]
@jxnblk 

still doesn't work

both this:

```js
export default {
  fonts: {
    body: '"Source Sans Pro", "Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    monospace: '"Fira Code", monospace',
    heading: 'inherit'
  },
  radii: {
    small: 10,
    large: 40
  },
  buttons: {
    primary: {
      background: 'black',
      color: 'white',
      borderRadius: 40
    },
    secondary: {
      color: 'white',
      background: 'blue',
      variant: 'buttons.primary'
    }
  },
  fontSizes: [12, 16, 20, 24, 'calc(1.8em + 2vw)', 'calc(3em + 5vw)'],
  space: [0, 4, 8, 14, 24, 36]
}
```

![image](https://user-images.githubusercontent.com/35937217/65060709-105c3e00-d981-11e9-9d27-47d696695305.png)

And this:

```js
export default {
  fonts: {
    body: '"Source Sans Pro", "Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
    monospace: '"Fira Code", monospace',
    heading: 'inherit'
  },
  radii: {
    small: 10,
    large: 40
  },
  buttons: {
    primary: {
      background: 'black',
      color: 'white',
      borderRadius: 'large'
    },
    secondary: {
      color: 'white',
      background: 'blue',
      variant: 'buttons.primary'
    }
  },
  fontSizes: [12, 16, 20, 24, 'calc(1.8em + 2vw)', 'calc(3em + 5vw)'],
  space: [0, 4, 8, 14, 24, 36]
}
```

![image](https://user-images.githubusercontent.com/35937217/65060755-236f0e00-d981-11e9-9382-7dca0747c95e.png)

It looks like `borderRadius: large` doesn't work too

UPD: sorry for being a bit stupid, I didn't have experience with design systems :)

**Comment by jxnblk** [comment]
Here is a working example: https://codesandbox.io/s/rebass-sandbox-gvs14

**Comment by talentlessguy** [comment]
> Here is a working example: https://codesandbox.io/s/rebass-sandbox-gvs14

Thanks for demo!

I finally found what the hell was going on

![image](https://user-images.githubusercontent.com/35937217/65061808-5a462380-d983-11e9-9afc-af6e47bf5236.png)

Is it a problem of styled-components?
