### ISSUE TITLE
Website is not available in Russia

### ISSUE THREAD

**Issue by talentlessguy** [rebassjs/rebass#734]
Because RKN blocked some subnet of IPs where Netlify has its CDN, rebassjs.org is blocked in Russia. I can use VPN of course but it is better to setup redirects to now.sh in case request is from Russia (if it is possible)

[Netlify forum topic](https://community.netlify.com/t/netlify-cdn-or-dns-blocked-in-russia/372/18)

**Comment by jxnblk** [comment]
Thanks for the heads-up! Since this sounds like an issue with Netlify, I'm not sure there's much I can do from here

**Comment by talentlessguy** [comment]
:(
