### ISSUE TITLE
outlineColor doesn't read values from theme for Input component

### ISSUE THREAD

**Issue by damnjan** [rebassjs/rebass#735]
When providing `outlineColor` to `Input` component via `sx` prop, the value should be read from the theme, but it is being ignored. Only native values work.
```jsx
theme = {
  colors: {
    primary: '#22aadd'
}

...

<Input sx={{outlineColor: 'primary'}} /> // Doesn't work
<Input sx={{outlineColor: 'red'}} /> // Works
```
Demo:
https://codesandbox.io/embed/smoosh-violet-mpyny

**Comment by jxnblk** [comment]
Currently `outlineColor` isn't handled by `@styled-system/css` (see https://github.com/styled-system/styled-system/blob/master/packages/css/src/index.js#L43-L118), but I'd accept a PR. In the meantime, you can use [functional values](https://theme-ui.com/sx-prop#functional-values)
