### ISSUE TITLE
adding styles using "css" is not working

### ISSUE THREAD

**Issue by Kalpana-Nagan** [rebassjs/rebass#736]
Just wondering if I can get example for use of CSS prop, as there is only example for "sx" prop in the document.

I tried as below:

```
<Button variant={variant}
    type={type}
    width={width}
     css={{
      cursor: 'pointer',
    }}
 >
 {children}
</Button>
```

**Comment by jxnblk** [comment]
The example you have here is how the `css` prop *should* work

**Comment by Kalpana-Nagan** [comment]
But dint work for me when I used css prop as above,it would be great if you can provide example or code snippet, Just to make sure I'm using it correctly.
