### ISSUE TITLE
Heading style properties are not being parsed

### ISSUE THREAD

**Issue by talentlessguy** [rebassjs/rebass#737]
When I use `<Heading />` I get this weird styling for `h2`:

```jsx
<Heading textAlign="center" as="h2" fontSize={['1.5em', '2.8em', '4.5em']}>
  Log In
</Heading>
```

![image](https://user-images.githubusercontent.com/35937217/65276149-d2514c80-db2f-11e9-8282-8311236ee7c4.png)

I use `rebass/styled-components` everywhere:

```jsx
import React from 'react'
import { Box, Flex, Heading } from 'rebass/styled-components'
import { Input } from '@rebass/forms/styled-components'

const Login = () => (
  <Flex alignItems="center" justifyContent="center" flexWrap="wrap">
    <Box as="form">
      <Heading textAlign="center" as="h2" fontSize={['1.5em', '2.8em', '4.5em']}>
        Log In
      </Heading>
      <Input />
    </Box>
  </Flex>
)

export default Login
```

I have `babel-plugin-styled-components` installed. What am I doing wrong?

**Comment by talentlessguy** [comment]
Dumb me, forgot to configure babel plugin

**Comment by talentlessguy** [comment]
Still happens even with babel plugin :/

Babelrc:

```js
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "styled-components",
      {
        "ssr": true,
        "displayName": true,
        "preprocess": true
      }
    ]
  ]
}
```

theme.js:

```js
// ...
  text: {
    heading: {
      fontFamily: 'fonts.heading',
      fontWeight: 800,
      lineHeight: 1
    }
  }
// ...
```

some_page.jsx:

```jsx
import React, { Fragment } from 'react'
import { Flex, Heading, Box } from 'rebass/styled-components'

// ...

<Heading as="h1" fontSize={['4em', '6em', '8em']}>
  Text
</Heading>
```


![image](https://user-images.githubusercontent.com/35937217/65897908-03940d00-e3b9-11e9-9da4-0e7c4252115d.png)

**Comment by talentlessguy** [comment]
I noticed that Rebass ignores `theme.text.heading`. Should it be like that?

**Comment by epilande** [comment]
> I noticed that Rebass ignores `theme.text.heading`. Should it be like that?

Sounds related to https://github.com/rebassjs/rebass/pull/754

**Comment by talentlessguy** [comment]
> > I noticed that Rebass ignores `theme.text.heading`. Should it be like that?
> 
> Sounds related to #754

Yup. Glad there is a fix already. Now need to wait for merging...

**Comment by talentlessguy** [comment]
Fixed! Closing
