### ISSUE TITLE
Reflexbox-Box Generates 2 Style Tags

### ISSUE THREAD

**Issue by nelsieborja** [rebassjs/rebass#741]
Happens when using both `sx` and a style prop for adding responsive styles.

Component:
```
<Box
    fontSize={[0, 2]}
    sx={{
        whiteSpace: [null, 'nowrap'],
    }}
/>
```

Output:
```
<style>
@media screen and (min-width: 40em)
.css-g9chlb {
    font-size: 16px;
}
</style>

<style>
@media screen and (min-width: 40em)
.css-g9chlb {
    white-space: nowrap;
}
</style>
```

Although this may not appear as an issue, is it possible to optimize it by combining them into 1 style declaration. Imagine you have multiple occurrences of this which is not ideal I believe

**Comment by jxnblk** [comment]
This is how Emotion generates style tags and not related to code in this repository. They do a lot of things like this to optimize for performance, but you can ask a question on their repo
