### ISSUE TITLE
Where is the code which triggers change of the "checked" props

### ISSUE THREAD

**Issue by tabomors** [rebassjs/rebass#766]
Hello! Where can i find the code which triggers change of the `checked` property? Seems like there is no code for it inside actual `Switch` component https://github.com/rebassjs/rebass/blob/master/packages/forms/src/index.js#L321.
Judging by the screenshot it should work out of the box, but it's not, which makes sense. Switch's documentation is a bit confusing to me.
![image](https://user-images.githubusercontent.com/15915715/66205859-2bd08400-e6b7-11e9-80f0-70de9200ddf8.png)
Thanks for the future reply!

**Comment by jxnblk** [comment]
Docs are incomplete, but it's an uncontrolled component, you can use the `checked` and `onClick` props to hook it into state

**Comment by tabomors** [comment]
Got it, thanks
