### ISSUE TITLE
Support size prop (custom prop)

### ISSUE THREAD

**Issue by Ilaiwi** [rebassjs/rebass#778]
Hi,

Thank you for the great package. I've seen [custom prop name](https://styled-system.com/variants#custom-prop-name) in `styled-system`. I am trying to support size prop for components variants like [`Button`](https://rebassjs.org/button).

I am not sure if this can be done via the current implementation or if it requires adding a new feature to rebass.

Thank you.

**Comment by jxnblk** [comment]
The `size` prop is built in and should set `width` and `height` for any of the components. You can use the `variant` prop to customize the variant used for the component

**Comment by Ilaiwi** [comment]
@jxnblk so I would do something like 
```
<Button varaint="primary.md"></Button>
<Button varaint="primary.xs"></Button>
<Button varaint="primary.lg"></Button>
```
can't it be like:
```
<Button varaint="primary" size="md"></Button>
<Button varaint="primary" size="xs"></Button>
<Button varaint="primary" size="lg"></Button>
```

**Comment by jxnblk** [comment]
Sorry for the delay. Only one variant can be passed to each component, and the `size` prop is part of Styled System's `layout` function. You might be able to use custom variants with Styled System to add a bespoke/custom props API
