### ISSUE TITLE
Document `tx` prop?

### ISSUE THREAD

**Issue by herrstucki** [rebassjs/rebass#779]
Hi! I noticed that internally, rebass uses the `tx` prop from reflexbox for scoped variants. For example, if I wanted to create a custom component that exposes variants, I could do

```js
// Without `tx`
const FancyBox = ({ variant, ...etc }) => <Box variant={`fancybox.${variant}`} {...etc} />

// With `tx`
const FancyBox = ({ variant, ...etc }) => <Box tx="fancybox" variant={variant} {...etc} />
```

Is this something that is officially supported (and thus should be documented) or not?

**Comment by jxnblk** [comment]
This is a private API and may break at any point so it should *not* be documented or used externally

**Comment by herrstucki** [comment]
OK, thanks for the feedback! 👍
