### ISSUE TITLE
Checkbox doesn't work by itself

### ISSUE THREAD

**Issue by mtt87** [rebassjs/rebass#780]
If you remove the `Label` wrapping a `Checkbox` it doesn't work by itself, is there a specific reason or is it a bug?

https://codesandbox.io/embed/fancy-http-vxi96

**Comment by jxnblk** [comment]
The `<label>` element is required when using `<input type='checkbox' />`

**Comment by mtt87** [comment]
Understand, thank you for reminding me 😄 

Sort of related, the switch component is instead working by itself as standalone without a `label`, is that intended?

That said, for some reason I can't make it work with Storybook, quite weird, anything that comes on top of your mind that might break it?

I can create a codesandbox later to reproduce

Thank you

**Comment by mtt87** [comment]
I can close the issue, I'm just curious about the Switch behaving differently but it's not really an issue. Thank you
