### ISSUE TITLE
Some box props are rendered into DOM attributes

### ISSUE THREAD

**Issue by salomvary** [rebassjs/rebass#795]
The following snippet renders not only CSS but also passes on some of the props into the HTML DOM without change:

```
      <Box color='white' bg='secondary' p={3} height={40}>
        Hello
      </Box>
```

results in

```
<div color="white" height="40" class="sc-bdVaJa fdRkHK">Hello</div>
```

Demo:
https://codesandbox.io/s/rebassstyled-components-example-91o7r

Might be related to using `rebass/styled-components`.

**Comment by jxnblk** [comment]
See https://styled-system.com/guides/removing-props-from-html

**Comment by jxnblk** [comment]
Also, you can use the Emotion version to avoid this issue

**Comment by salomvary** [comment]
Ouch. That seems like a very long ongoing issue with styled-component. Thanks for the quick response anyway.
