### ISSUE TITLE
borderRadius on Button causes warning

### ISSUE THREAD

**Issue by steverecio** [rebassjs/rebass#796]
If I render a rebass Button `as` as react-router NavLink, I get the following warning:

> React does not recognize the `borderRadius` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `borderradius` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

```
import { Button } from 'rebass';
import { NavLink } from 'react-router-dom';

export function NavButton(props) {
   return (
     <Button to={props.to} as={NavLink} />
   );
}
```

Is there any way to prevent the default borderRadius prop on the Button from flowing into the NavLink? Maybe a way to filter the props passed through? Like an `as_props` argument or something? For instance, the only prop I want passed through to the NavLink is the `to` prop.

**Comment by jxnblk** [comment]
If you're using `styled-components`, it might be related to this: https://styled-system.com/guides/removing-props-from-html#styled-components (there is a link to the relevant `styled-components` issue)

If you have the option, I'd recommend using the Emotion version nowadays
