### ISSUE TITLE
Confusion around width prop % shorthands and theme.sizes

### ISSUE THREAD

**Issue by salomvary** [rebassjs/rebass#797]
The following situation caused me a bit of head-scratching. (Note that I am new to both Rebass and Styled Components.)

Given a theme that contains `sizes` in an array form and also has breakpoints defined, like:

```
{
    breakpoints: ['1024px', '1280px', '1400px'],
    sizes: [0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80]
}
```

What is the expected outcome of this?
```
      <Box width={[0, 1/2, 1, 2]}>
        Test
      </Box>
```

Apparently `theme.sizes` wins over [width percentage shorthands](https://rebassjs.org/props#width) resulting in `width={['0px', '50%', '8px', '16px']}`. Is this expected? Should this rather result in `width={['0%', '50%', '100%', '16px']}`? Is/should this behavior be documented somewhere?

As the workaround is easy by using `'100%'` instead of `1` to still get percentage widths this is not a big deal but a less confusing API might be considered for a next major version. Maybe a separate "magicWidth" property?

**Comment by jxnblk** [comment]
Sorry for the delay! Generally, I'd recommend using string values for percentage-based widths, since the fractional syntax is less widely known. And, as you've figured out, only numbers between `0` and `1` will be converted to percentages
