### ISSUE TITLE
img width and height

### ISSUE THREAD

**Issue by paynecodes** [rebassjs/rebass#805]
It's a fairly common and recommended practice to pass `width` and `height` to html `<img>` tags. I don't see a way to accomplish this currently, so I'd like to propose an `htmlWidth` and `htmlHeight` prop. What do you think?

**Comment by jxnblk** [comment]
I'd rather not invent new naming conventions for these, but this is a limitation with the current API. My recommendation would be to use a standard `<img>` element for cases where you need this -- with [Theme UI](https://theme-ui.com), the `width` and `height` props have been removed in favor of using the `sx` prop

**Comment by karlhorky** [comment]
Not only is this common practice, but it improves the performance of your page (avoiding reflow):

> adding width and height attributes to the img helps the browser avoid reflow by painting a placeholder to the screen:

https://web.dev/native-lazy-loading#image-loading

Images using `loading="lazy"` will also result in a warning in the console in the Chrome Devtools:

> [Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323
