### ISSUE TITLE
Cannot combine mulitple pseudoclasses from different variants

### ISSUE THREAD

**Issue by talentlessguy** [rebassjs/rebass#835]
I have such theme settings:

```js
variants: {
    link: {
      default: {
        fontSize: '1em',
        margin: '1em',
        '&:hover': {
          cursor: 'pointer'
        }
      },
      light: {
        variant: 'variants.link.default',
        color: 'darkGray',
        '&:hover': {
          color: 'darkBlack'
        }
      },
      dark: {
        color: 'white',
        variant: 'variants.link.default',
        '&:hover': {
          color: 'lightGray'
        }
      }
    }
}
```

I expected `variants.link.default['&:hover']` to be combined with themes, not being overriden. So now links have color on hover but there is no pointer mouse.

Is it a bug or it should work like this?

**Comment by jxnblk** [comment]
IIRC this only handles shallow merging objects, so I don't think it's a bug, but perhaps the current API could be improved upon

**Comment by talentlessguy** [comment]
@jxnblk in what place are themes being processed (e.g. a package?). I can try making a PR with a fix but I need to know where to start

**Comment by jxnblk** [comment]
Closing this for now, but feel free to take a stab at a PR if you'd like to

**Comment by talentlessguy** [comment]
> Closing this for now, but feel free to take a stab at a PR if you'd like to

Could you please help me to get started on the repo? Where are themes being computed? in Rebass? or in some other package? I'd like to make a fix but I'm confused
