### ISSUE TITLE
Rebass 3.1.0 lost Padding and Margins

### ISSUE THREAD

**Issue by michaelcuneo** [rebassjs/rebass#853]
Just did an update to Rebass last week, and I've lost all support for Padding and Margins. Not sure what I've done, but it's dropped everything entirely, and there's no space between anything in my Flexes and Boxes and Text...

**Comment by jxnblk** [comment]
Can you link to a relevant code example and/or reproduction?

**Comment by jxnblk** [comment]
This sounds potentially like mismatched context -- feel free to reopen if you have a reproduction

**Comment by michaelcuneo** [comment]
Sorry for the delay in reply. I just went on leave for ages and just got back recently. I'm just using it in it's usual format... i.e. this is one of my flex boxes.

```
      <Flex
        key="ContributeFlexWrapper"
        flexWrap="wrap"
        width={[1]}
        p={[2, 4, 6]}
        style={{
          overflow: 'scroll',
          width: '100vw',
          height: '100vh',
          color: this.props.mode ? 'black' : 'white',
        }}
      >
```

If I provide a specific pixels i.e. p={['100px', '150px', '200px']} it will work... but won't work with breakpoint ratios.

**Comment by jxnblk** [comment]
I don't see anything wrong with the example above, but it would still be helpful to have a live reproduction since I suspect the issue might be with mismatched contexts and/or missing theme context

**Comment by michaelcuneo** [comment]
Looks like, when I add a style to any rebased component within my entire app it loses the ability to read the entire padding and margin from all rebass components.

**Comment by michaelcuneo** [comment]
@jxnblk I have found the problem. For some reason inline style destroys the component. If I create a styled-component it works fine, but if I inline the style, it breaks the component. I've had to remove all inline styles to make it work and restore it's component functionality.
