### ISSUE TITLE
Flex does not seem to respect display:none

### ISSUE THREAD

**Issue by kevinswarner** [rebassjs/rebass#854]
https://codesandbox.io/s/morning-leftpad-47jhp

It appears that the Flex component does not respect the display:none CSS display property when setting it to "none". Actually, I think that the display: 'flex' just seems to always take precedence. In the example, you will see that using the !important flag does seem to work.

I am not sure if this is a bug or intended behavior. Using the !important flag seems to resolve the issue, but wanted to bring this up. Thanks!

**Comment by jxnblk** [comment]
The only difference between `Flex` and `Box` is that the former sets `display: flex`. If you want to change the display property, you can use the `Box` component instead

**Comment by kevinswarner** [comment]
I understand. However, if you want to dynamically "hide" a Flex container following the approach of "display:none", then that does not work, unless you use the !important flag. Again, not an issue as I was able to use the !important flag.

**Comment by Baltino** [comment]
I agree. I think the issue relies in that the original component is setting the prop attributes at the end:
For example
`<Flex {...props} sx={{ display: "flex"}} />`
