### ISSUE TITLE
React 15 compatibility?

### ISSUE THREAD

**Issue by dk-jlew** [rebassjs/rebass#860]
Hello, great work you've done here! I am evaluating rebass for use in implementing our own design system/component library.  We are mostly on React 16, but have one large application that is still on React 15.  From what I can tell, the main hangup is not in rebass, but that Emotion requires React Context to exist (even if you don't use it.).  Do you see any way out of this, short of leaving the React 15 project behind?
Thanks!

**Comment by jxnblk** [comment]
Just a thought: If you need to support React 15, you could consider installing an older version of Rebass, which should have a similar API to current, then migrate to the latest once you’re on React 16. Otherwise you could look into using styled-system directly to build your own React 15 compatible components

**Comment by dk-jlew** [comment]
Thanks, will look into those options. Is there a way to achieve the theming support where ThemeProvider could be used if Context is available, but could be passed as a direct prop where not?

**Comment by jxnblk** [comment]
You can generally pass a `theme` prop to `styled-components` or `@emotion/styled` components if needed

**Comment by dk-jlew** [comment]
Right, maybe I'm confused about the dependency situation, but I was under the impression that either of those options would try and initialize ThemeConsumer even if ThemeProvider is never used by the application, and therefore have a hard dependency on react 16.4.  I'll dig in some more.

**Comment by jxnblk** [comment]
Closing this for now, but feel free to comment if you've found any solutions for using React 15
