### ISSUE TITLE
as prop breaking extended rebass components

### ISSUE THREAD

**Issue by coreybruyere** [rebassjs/rebass#872]
When extending a rebass component, e.g, `<Box>` and passing the `as` prop on the newly created, extend component, e.g, a `<Position>` component, and adding an `as` prop all Box styles are lost. I've created a Codesandbox demo in the link below. 

```
import { Box, Flex, Heading, Text, Button } from "rebass";
import { position } from "styled-system";

// Downgrade to 3.2.2 and all Box props passed to the Article component are properly rendered.
// Upgrade to 4.0.7 and notice only positioning props are being passed down.
const Article = styled(Box)(position);
```

Codesandbox:
https://codesandbox.io/s/sandbox-b417m

Spectrum chat:
https://spectrum.chat/styled-system/general/as-prop-breaking-extended-box-prop-styles~8cbd9ebe-b840-4610-945c-acd1e354014d

**Comment by jxnblk** [comment]
Are you using Emotion or Styled Components?

**Comment by coreybruyere** [comment]
Styled Components

**Comment by jxnblk** [comment]
You'll need to import from `rebass/styled-components` if you aren't using Emotion

**Comment by coreybruyere** [comment]
@jxnblk - Yup, that was it. I recall reading that another time when reading through the docs. Can you point to a write up or an explanation for the switch from styled-components to Emotion?
