### ISSUE TITLE
RTL support for Select

### ISSUE THREAD

**Issue by mhmdAljefri** [rebassjs/rebass#873]
I was working on Admin Dashboard with Rebass Form Components It's looks good. But I faced an Issue on RTL layout. The svg Icon goes outer select input.

and I override the position of svg by using 
{
margin-inline-start: -28px
} 
instead of 
{
margin-left: -28px
}
to Solve this issue

**Comment by jxnblk** [comment]
Thanks for the suggestion. I don't plan on adding support for this, but if you'd like to open a PR, feel free to
