### ISSUE TITLE
Upgrade to emotion v11

### ISSUE THREAD

**Issue by stramel** [rebassjs/rebass#875]
Just wanted to bring up awareness that Emotion has started to release some `next` builds for v11. It sounds like it _should_ be coming in the next month for official release.

Motivation behind this is that `docz` has `reflexbox` in it's dependency tree and relies on v10 of emotion. Trying to get all dependencies updated when it lands.

**Comment by jxnblk** [comment]
Thanks! This is on our radar, but until the official version is released, I'm not planning on making any changes to the current version. I would assume that moving to Emotion 11 would require a major version bump in Rebass

**Comment by mrtnpro** [comment]
Since Emotion 11 has been officially released by now, can we reopen this issue @jxnblk?
