### ISSUE TITLE
Issue with Variants of Buttons

### ISSUE THREAD

**Issue by Kalpana-Nagan** [rebassjs/rebass#896]
Hi,

I recently updated my Rebass V3 to V4 and found that variants are not getting applied, In migration document I found saying "The undocumented theme keys for Box, Flex, Text, Heading, Link, Button, Image, and Card are no longer supported. Use variants instead." Can  I get example for this.

Existing code Rebass V3:

`export const buttons = {
  primary: {
    color: colors.pureWhite,
}
secondary: {
color: colors.blue,
}
}
`

Rebass V4:

`export const variants = {
  Button: {
      primary: {
    color: colors.pureWhite,
}
secondary: {
color: colors.blue,
}
}
}`

**Comment by jxnblk** [comment]
The Button components variants should be defined in the `theme.buttons` object: https://rebassjs.org/variants
