### ISSUE TITLE
Is it possible to use responsive array with alias?

### ISSUE THREAD

**Issue by seeden** [rebassjs/rebass#898]
I am not able to use alias with responsive array as alias.

Here is small example of my problem.

 **Theme:**
```js
  breakpoints: ['40em', '52em', '64em', '80em'],
  sizes: {
    container: [null, '540px', '720px', '960px', '1140px'],
  },
```

**Component:**
```js
import React from 'react';
import { Flex } from 'rebass/styled-components';

export default function GridContainer(props: Props) {
  const { children } = props;

  return (
    <Flex maxWidth="container">
      {children}
    </Flex>
  );
};
```

It is working when I use responsive array directly.
```js
<Flex maxWidth={[null, '540px', '720px', '960px', '1140px']} >
```

and it is working as well when I use single value in the theme
```js
  breakpoints: ['40em', '52em', '64em', '80em'],
  sizes: {
    container: '720px',
  },
```

Is it posible to use alias instead of array? I would like to define these values inside theme.

**Comment by seeden** [comment]
I was able to use it as variant but it will be nice feature if I can use it directly as property. Maybe it is nice feature for feature release. :)

```js
  variants: {
    container: {
      maxWidth: [null, '540px', '720px', '960px', '1140px'],
    },
  },
```

```js
import React from 'react';
import { Flex } from 'rebass/styled-components';

type Props = {
  children: React.ReactNode,
};

export default function GridContainer(props: Props) {
  const { children } = props;

  return (
    <Flex variant="container">
      {children}
    </Flex>
  );
};
```

**Comment by jxnblk** [comment]
You cannot define responsive values in theme scales like your first example. If you want to encapsulate responsive styles in your theme, you'll need to use variants, like in the second example

**Comment by seeden** [comment]
Thanks, no problem
