### ISSUE TITLE
Documentation pages broken and missing styles

### ISSUE THREAD

**Issue by mrchess** [rebassjs/rebass#902]
The documentation pages seem to be broken and missing styles. Screenshot attached:

<img width="498" alt="rebass" src="https://user-images.githubusercontent.com/106922/73297523-b8103500-41d9-11ea-8e40-b8f55485ec4f.png">

**Comment by jxnblk** [comment]
Define *broken*

**Comment by mrchess** [comment]
It used to show pictures of the components in their respective sections, and you could interact with them. 

For example, you used to be able to visit the *Demo* section and flip through the themes. 

Now you can't do any of that, and there are no component previews.

See the demo section below, where it no longer shows styles or lets you flip through themes.

<img width="611" alt="demo" src="https://user-images.githubusercontent.com/106922/73302343-7df76100-41e2-11ea-8195-9746a61458b2.png">

**Comment by mrchess** [comment]
It used to look something like this. Notice how the sidebar is themed, and the main page is themed. It looks like a CSS file is missing.

<img width="639" alt="old" src="https://user-images.githubusercontent.com/106922/73302595-df1f3480-41e2-11ea-91fc-65bbbcbe0d58.png">

**Comment by jxnblk** [comment]
Sorry that was just a joke -- it looks pretty cool to me though :)

**Comment by jxnblk** [comment]
Should be back up now, thanks!

**Comment by mrchess** [comment]
Thanks. Looks better! There is still an issue with this though. Clicking on a item on the left navigation menu does not sed you there on first click.

**Steps to reproduce:**
1. Open https://rebassjs.org/flex
2. Click on "Getting Started", or any item on the left menu

**Expected:**
Sends you to "Getting Started Page"

**Actual:**
Nothing happens. You need to click "Getting Started" a second time, to actually get sent there. Basically you need to click left nav items twice, before getting sent there.
