### ISSUE TITLE
Migrate to styled-components

### ISSUE THREAD

**Issue by nainardev** [rebassjs/rebass#916]
faster and lighter than emotion

**Comment by jxnblk** [comment]
You can use [`rebass/styled-components`](https://rebassjs.org/guides/styled-components) for Styled Components

**Comment by nainardev** [comment]
Also @jxnblk, i had a question,
`rebass` "somewhat" looks like `Bootstrap`

Is that intentional?

**Comment by nainardev** [comment]
Like `button`
