### ISSUE TITLE
Text wrapped by styled does not pass props

### ISSUE THREAD

**Issue by BarnabasChun** [rebassjs/rebass#920]
If the Text component is wrapped by styled from styled components, rebass props passed to it don't seem to be applying.

Example: https://codesandbox.io/s/competent-dust-mkr1p

**Comment by jxnblk** [comment]
I suspect this might have something to do with how Styled Components handles the `as` prop, but not sure there's anything that can be done from this library

**Comment by BarnabasChun** [comment]
> I suspect this might have something to do with how Styled Components handles the `as` prop, but not sure there's anything that can be done from this library

Well this issue arose after upgrading to v4.x as you can see in this demo, downgrading to v3.x has everything working as expected: https://codesandbox.io/s/affectionate-frost-gdjxf

**Comment by jxnblk** [comment]
Rebass v4 components aren't really meant to be used with the `styled` HOC API -- if you want to extend a component, you can use the `sx` prop: https://rebassjs.org/extending

**Comment by BarnabasChun** [comment]
I see, missed that note in the documentation. Just an odd inconsistency since extending the Box with styled + as prop works fine.

Thanks for the discussion, I'll close this (:
