### ISSUE TITLE
Local file for background image in a Box container

### ISSUE THREAD

**Issue by fmeehan** [rebassjs/rebass#931]
Hi! 

Is there a way to refer to a local image as the background image in a container? 

As in the following statements: 

<Box
  sx={{
    px: 4,
    py: 6,
    backgroundImage: 'url(https://source.unsplash.com/random/1024x768?forest)',
    backgroundSize: 'cover',
    borderRadius: 8,
    color: 'white',
    bg: 'gray',
  }}>
</Box>

Tried all kind of combinations and could not find a Rebass example for local image files.

The file reside in same directory as the script, ../MainCover.jpg. 

Thanks in advance, 

François

**Comment by jxnblk** [comment]
Any string value for `backgroundImage` will be evaluated in the CSS of your site, so it depends on how you have your site, build setup, deployments, etc. set up

**Comment by fmeehan** [comment]
Hi, 

I see, so I did: 

backgroundImage: 'url(../../mainCover.jpg)',

And it is working. 

Thanks.
