### ISSUE TITLE
ui library built with rebass

### ISSUE THREAD

**Issue by codejamninja** [rebassjs/rebass#935]
Rebass is super because it is so primitive, yet so powerful. However, one major drawback is there are no large ui libraries built with rebass.

Yes, I know that doesn't mean I can't use rebass with another ui library, but I believe there is a place for a large well supported ui library built on top of rebass.

When it comes to more advanced components like date pickers and such, I'm forced to look outside of rebass, or built it from scratch. This creates a problem when I am trying to build an application with a consistent design because I'm picking and pulling components from lots of ui systems.

I know rebass will never build advanced components, because that is not the job of rebass, but is there any plans for a larger ui library built on top of rebass?

**Comment by jxnblk** [comment]
This was the premise behind the original library 5 years ago, but to my knowledge, no one has really extended Rebass in this sort of way. This was part of the idea behind Styled System, which other libraries like Chakra UI are built with -- hope that makes sense

**Comment by codejamninja** [comment]
Is chakra using rebass?
