### ISSUE TITLE
Rebass components pick up theme values from ThemeProvider when using styled-components, but not when using emotion-theming

### ISSUE THREAD

**Issue by baddox** [rebassjs/rebass#936]
**Edit: jxnblk offered [the solution below](https://github.com/rebassjs/rebass/issues/936#issuecomment-606047060).**

I'm currently unable to get theme values to work in Rebass components when wrapped in emotion-theming's `ThemeProvider`. The generated CSS has the theme's color names, which are of course not valid CSS color names.

When I use Rebass' styled components and the styled-components `ThemeProvider`, everything works fine (and we're actually using this in production now).

If I use emotion-theming's `useTheme` hook, it correctly gets my theme from context, and the theme values start working if I pass that theme in directly as a prop to a Rebass component (see code below).

I'm still struggling to get a complete minimal example project to demonstrate the problem, but below is roughly the code I've been trying. If anyone has any ideas for troubleshooting this I would appreciate it!

```jsx
const theme = {
  colors: {
    backgroundDark: 'darkGreen',
  },
};

//
// 👍 Everything works fine with styled-components.
//
import { ThemeProvider as StyledComponentsThemeProvider } from 'styled-components';
import { Button as StyledComponentsButton } from 'rebass/styled-components';

export const StyledComponentsDemo = () => {
  const Button = () => {
    return (
      <StyledComponentsButton backgroundColor="backgroundDark">
        This button has a dark green background.
      </StyledComponentsButton>
    );
  };
  return (
    <StyledComponentsThemeProvider theme={theme}>
      <Button />{' '}
    </StyledComponentsThemeProvider>
  );
};

//
// 😢 It doesn't work with emotion-theming.
//
import { ThemeProvider as EmotionThemeProvider } from 'emotion-theming';

import { Button as EmotionButton } from 'rebass';

export const EmotionDemo = () => {
  const Button = () => {
    return (
      <EmotionButton backgroundColor="backgroundDark">
        This button should have a dark green background, but it doesn't! The
        generated CSS has `backgroundColor: "backgroundDark"` which is of course
        invalid.
      </EmotionButton>
    );
  };
  return (
    <EmotionThemeProvider theme={theme}>
      <Button />
    </EmotionThemeProvider>
  );
};

// 🤔 This works if I get the theme from context using the hook and pass it
// directly to the Rebass component.
import { useTheme } from 'emotion-theming';

export const EmotionDemoWithHook = () => {
  const Button = () => {
    const themeFromContext = useTheme();
    return (
      <EmotionButton backgroundColor="backgroundDark" theme={themeFromContext}>
        This button has a dark green background.
      </EmotionButton>
    );
  };
  return (
    <EmotionThemeProvider theme={theme}>
      <Button />
    </EmotionThemeProvider>
  );
};

```

**Comment by baddox** [comment]
I should add my versions from `package.json`:

```
"rebass": "^4.0.7",
"styled-components": "^5.0.1",
"emotion-theming": "^10.0.27",
```

**Comment by jxnblk** [comment]
Sometimes contexts can mismatch if there is more than one version of `@emotion/core` installed locally. Can you run `npm ls` or `yarn list` to check to make sure only one copy of Emotion is installed?

**Comment by baddox** [comment]
@jxnblk Wouldn't you know it, I had an old `react-select 2.x` that was bringing in `emotion 9.x` and that was causing the issue! Thanks so much for the tip.
