### ISSUE TITLE
Conflict versions packages jest

### ISSUE THREAD

**Issue by IvanovRoman** [rebassjs/rebass#954]
When run command "lerna run start". Error occurs:

lerna ERR! yarn run start stderr:

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "jest": "24.9.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of jest was detected higher up in the tree:

  E:\Examples\Monorepositories\rebass\node_modules\jest (version: 25.3.0)

**Comment by jxnblk** [comment]
Looks like an issue with CRA, but you can check your dependencies with `npm ls` or `yarn list`
